import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){/*

 Copyright 2016 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
var Px="BANDWIDTH",Qx="CLOSED-CAPTIONS",Rx="EXT-X-BYTERANGE",Sx="EXT-X-ENDLIST",Tx="EXT-X-MEDIA-SEQUENCE",Ux="EXT-X-PLAYLIST-TYPE",Vx="EXT-X-STREAM-INF",Wx="EXT-X-TARGETDURATION",Xx="GROUP-ID",Yx="Guessing audio-only",Zx="SUBTITLES",$x="URI",ay="application/mp4",by=function(a,b){b=void 0===b?0:b;return b+10<=a.length&&73===a[b]&&68===a[b+1]&&51===a[b+2]&&255>a[b+3]&&255>a[b+4]&&128>a[b+6]&&128>a[b+7]&&128>a[b+8]&&128>a[b+9]?!0:!1},cy=function(a,b,c,d){this.c=a;this.type=b;this.a=c;this.b=d||null},
dy=function(a,b,c,d){this.id=a;this.name=b;this.a=c;this.value=void 0===d?null:d},ey=function(a,b){this.name=a;this.value=b},fy=function(a,b,c){return(a=a.getAttribute(b))?a.value:c||null},gy=function(a,b){var c=a.getAttribute(b);if(!c)throw new _.K(_.M,4,4023,b);return c.value},hy=function(a,b){this.b=b;this.a=a},iy=function(){this.a=0},oy=function(a,b,c){b=_.mf(b);b=b.replace(/\r\n|\r(?=[^\n]|$)/gm,"\n").trim();var d=b.split(/\n+/m);if(!/^#EXTM3U($|[ \t\n])/m.test(d[0]))throw new _.K(_.M,4,4015);
b=0;for(var e=1;e<d.length;e++)if(!jy.Hd(d[e])){var f=ky(a,d[e]);--a.a;if(ly.includes(f.name)){b=1;break}else f.name==Vx&&(e+=1)}e=[];for(f=1;f<d.length;)if(jy.Hd(d[f]))f+=1;else{var g=ky(a,d[f]);if(my.includes(g.name)){if(1!=b)throw new _.K(_.M,4,4017);d=d.splice(f,d.length-f);a=ny(a,c,d,e);return new cy(c,b,e,a)}e.push(g);f+=1;g.name==Vx&&(g.a.push(new ey($x,d[f])),f+=1)}return new cy(c,b,e)},ny=function(a,b,c,d){var e=[],f=[];c.forEach(function(g){/^(#EXT)/.test(g)?(g=ky(a,g),ly.includes(g.name)?
d.push(g):f.push(g)):jy.Hd(g)||(g=jy.Sc(b,g.trim()),e.push(new hy(g,f)),f=[])});return e},ky=function(a,b){var c=a.a++,d=b.match(/^#(EXT[^:]*)(?::(.*))?$/);if(!d)throw new _.K(_.M,4,4016,{invalidTag:b});var e=d[1],f=d[2];d=[];var g;if(f){f=new _.il(f);var h;(h=_.jl(f,/^([^,=]+)(?:,|$)/g))&&(g=h[1]);for(var l=/([^=]+)=(?:"([^"]*)"|([^",]*))(?:,|$)/g;h=_.jl(f,l);)d.push(new ey(h[1],h[2]||h[3]))}return new dy(c,e,d,g)},ry=function(){var a=this;this.f=this.h=null;this.W=1;this.j=new Map;this.S=new Set;
this.b=new Map;this.c=null;this.m="";this.C=new iy;this.R=0;this.l=new _.sg(function(){py(a)});this.g=qy;this.w=null;this.I=0;this.M=Infinity;this.o=new _.eg;this.N=[];this.A=new Map;this.v=!1;this.i=new Map;this.F=null;this.a=new _.E("clpp.hls.HlsParser");this.u=new Map},wy=function(a,b){var c,d,e,f,g,h,l,m,n,p,q;return _.z(function(t){if(1==t.a)return c=jy,d=sy,e=b.Ff,_.x(t,ty(a,e),2);if(3!=t.a){f=t.b;g=oy(a.C,f.data,f.uri);if(1!=g.type)throw new _.K(_.M,4,4017);l=(h=c.mb(g.a,Tx))?Number(h.value):
0;m=b.stream;return _.x(t,uy(a,b.jd,g,l,m.type,m.mimeType,m.codecs,m.keyInfo),3)}n=t.b;b.$a.replace(n);p=n[n.length-1];if(q=c.mb(g.a,Sx))vy(a,d.VOD),a.c.bb(p.endTime);_.y(t)})},zy=function(a,b){var c,d,e,f,g,h,l,m,n,p,q,t,u,A,D;return _.z(function(G){if(1==G.a){c=oy(a.C,b,a.m);if(1===c.type){a.u.set(a.m,c);var H=a.C,L=a.m,T=[],wa=[];wa.push(new ey(Px,"0"));wa.push(new ey($x,L));T.push(new dy(H.a++,Vx,wa));c=new cy(L,0,T)}return _.x(G,xy(a,c.a),2)}d=G.b;if(!a.h)throw new _.K(_.M,7,7001);a.h.filterAllPeriods([d]);
e=Infinity;f=0;g=Infinity;h=_.v(a.b.values());for(l=h.next();!l.done;l=h.next())m=l.value,e=Math.min(e,m.Nd),f=Math.max(f,m.Nd),m.stream.type!=_.k&&(g=Math.min(g,m.duration));a.g!=qy?(a.c=new _.nn(0,3*a.I,!0),a.c.b=!1):(a.c=new _.nn(null,0,!0),a.c.b=!0);yy(a);if(a.g!=qy){a.R=a.M;n=sy;a.g==n.LIVE&&(p=a.c.Xd,isNaN(a.f.availabilityWindowOverride)||(p=a.f.availabilityWindowOverride),a.c.Fb=p);for(q=0;95443.7176888889<=f;)q+=95443.7176888889,f-=95443.7176888889;if(q)for(a.a.debug("Offsetting live streams by",
q,"to compensate for rollover"),t=_.v(a.b.values()),l=t.next();!l.done;l=t.next())u=l.value,95443.7176888889>u.Nd?(a.a.debug("Offset applied to",u.stream.type),u.stream.presentationTimeOffset=-q,u.$a.offset(q)):a.a.debug("Offset NOT applied to",u.stream.type)}else for(a.c.bb(g),a.c.offset(-e),A=_.v(a.b.values()),l=A.next();!l.done;l=A.next())D=l.value,D.stream.presentationTimeOffset=e,D.$a.offset(-e),_.mn(D.$a,g);a.w={presentationTimeline:a.c,periods:[d],offlineSessionIds:[],minBufferTime:0};_.y(G)})},
xy=function(a,b){var c,d,e,f,g;return _.z(function(h){switch(h.a){case 1:c=jy;d=c.pc(b,"EXT-X-MEDIA");e=c.pc(b,Vx);for(var l=_.v(e),m=l.next();!m.done;m=l.next()){var n=m.value,p=fy(n,"AUDIO");m=fy(n,"VIDEO");var q=fy(n,Zx);n=Ay(a,n);if(q){var t=By(_.k,n);a.i.set(q,t);_.ol(n,t)}p&&(q=Cy(_.Ib,n),a.i.set(p,q));m&&(p=Cy(_.Xd,n),a.i.set(m,p))}return _.x(h,Dy(a,d),2);case 2:l=jy.Qe(d,Qx);l=_.v(l);for(m=l.next();!m.done;m=l.next())m=m.value,p=fy(m,"LANGUAGE")||_.Od,p=_.vl(p),q=gy(m,Xx),m=gy(m,"INSTREAM-ID"),
a.A.get(q)||a.A.set(q,new Map),a.A.get(q).set(m,p);return _.x(h,Ey(a,e),3);case 3:return f=h.b,_.x(h,Fy(a,d),4);case 4:return g=h.b,h["return"]({startTime:0,variants:f,textStreams:g,thumbStreams:[]})}})},Fy=function(a,b){var c,d,e,f,g,h,l,m,n,p,q,t;return _.z(function(u){if(1==u.a)return c=jy.Qe(b,Zx),d=c.map(function(A){var D,G;return _.z(function(H){if(1==H.a)return H.c=2,_.x(H,Gy(a,A),4);if(2!=H.a)return D=H.b,H["return"](D.stream);G=_.Ce(H);throw G;})}),_.x(u,Promise.all(d),2);e=u.b;f=_.v(c);
for(g=f.next();!g.done;g=f.next())if(h=g.value,l=gy(h,Xx),m=a.i.get(l))if(n=a.j.get(l))for(p=_.v(n),q=p.next();!q.done;q=p.next())t=q.value,t.stream.codecs=m;return u["return"](e.filter(function(A){return A}))})},Dy=function(a,b){var c;return _.z(function(d){if(1==d.a)return b=b.filter(function(e){var f=fy(e,$x)||"";return fy(e,"TYPE")!==Zx&&""!==f}),b.length?d=_.x(d,Gy(a,b[0]),2):(d.a=2,d=void 0),d;c=b.slice(1).map(function(e){return Gy(a,e)});return _.x(d,Promise.all(c),0)})},Ey=function(a,b){var c,
d,e,f,g,h,l;return _.z(function(m){if(1==m.a)return c=_.mi,b.sort(function(n,p){var q=Number(gy(n,Px)),t=Number(gy(p,Px));return q-t}),d=function(n){var p,q,t,u,A,D,G;return _.z(function(H){return 1==H.a?(p=fy(n,"FRAME-RATE"),q=Number(gy(n,Px)),t=fy(n,"RESOLUTION"),u=_.v(t?t.split("x"):[null,null]),A=u.next().value,D=u.next().value,_.x(H,Hy(a,n,t,p),2)):(G=H.b)?H["return"](Iy(a,G.audio,G.video,q,A,D,p)):H["return"]([])})},_.x(m,d(b[0]),2);if(3!=m.a){e=m.b;f=[];for(g=1;g<b.length;g++)f.push(d(b[g]));
return _.x(m,Promise.all(f),3)}h=m.b;l=h.reduce(c.wd,e);l=l.filter(function(n){return null!=n});return m["return"](l)})},Hy=function(a,b,c,d){var e,f,g,h,l,m,n,p,q,t,u,A,D;return _.z(function(G){if(1==G.a)return e=_.ok,f=Ay(a,b),g=fy(b,"AUDIO"),h=fy(b,"VIDEO"),m=(l=g||h)&&a.j.has(l)?a.j.get(l):[],n={audio:g?m:[],video:h?m:[]},a.a.debug("Guessing stream type for",b.toString()),q=gy(b,$x),t=n.audio.find(function(H){return H.jd===q}),u=By(e.VIDEO,f),A=c||d||u,m.length||1!==f.length||A?!m.length&&1<f.length?
(a.a.debug("Guessing multiplexed audio+video"),p=e.VIDEO,f=[f.join(",")]):n.audio.length&&t?(a.a.debug(Yx),p=e.AUDIO):n.video.length?(a.a.debug(Yx),p=e.AUDIO):(a.a.debug("Guessing video-only"),p=e.VIDEO):p=e.AUDIO,_.x(G,Jy(a,b,f,p),3);2!=G.a&&(D=G.b);if(D)n[D.stream.type]=[D];else if(null===D)return a.a.debug("streamInfo is null"),G["return"](null);Ky(n);return G["return"](n)})},Ky=function(a){a=_.v(a.audio.concat(a.video));for(var b=a.next();!b.done;b=a.next()){b=b.value;var c=b.stream.codecs.split(",");
c=c.filter(function(d){return"mp4a.40.34"!=d});b.stream.codecs=c.join(",")}},Iy=function(a,b,c,d,e,f,g){c.forEach(function(D){if(D=D.stream)D.width=Number(e)||void 0,D.height=Number(f)||void 0,D.frameRate=Number(g)||void 0});b.length||(b=[null]);c.length||(c=[null]);var h=[];b=_.v(b);for(var l=b.next();!l.done;l=b.next()){l=l.value;for(var m=_.v(c),n=m.next();!n.done;n=m.next()){var p=n.value;n=l?l.stream:null;var q=p?p.stream:null,t=l?l.drmInfos:null,u=p?p.drmInfos:null;p=(p?p.jd:"")+" - "+(l?l.jd:
"");var A=void 0;if(n&&q)if(t.length&&u.length?0<_.Zi(t,u).length:1)A=_.Zi(t,u);else{a.a.warn("Incompatible DRM info in HLS variant.  Skipping.");continue}else n?A=t:q&&(A=u);a.S.has(p)?a.a.debug("Skipping variant which only differs in text streams."):(n=Ly(a,n,q,d,A),h.push(n),a.S.add(p))}}return h},Ly=function(a,b,c,d,e){return{id:a.W++,language:b?b.language:_.Od,primary:!!b&&b.primary||!!c&&c.primary,audio:b,video:c,bandwidth:d,drmInfos:e,allowedByApplication:!0,allowedByKeySystem:!0}},Gy=function(a,
b){var c,d,e,f,g,h,l,m,n,p,q,t,u;return _.z(function(A){if(1==A.a){c=gy(b,Xx);d="";e=gy(b,"TYPE").toLowerCase();f=_.ok;e==_.Dd&&(e=f.TEXT);e!==f.TEXT&&c&&a.i.has(c)&&(d=a.i.get(c));g=gy(b,$x);if(a.b.has(g))return A["return"](a.b.get(g));h=_.vl(fy(b,"LANGUAGE",_.Od));l=fy(b,"NAME");m=b.getAttribute("DEFAULT");n=b.getAttribute("AUTOSELECT");p=fy(b,"CHANNELS");q=e==_.Ib?p?parseInt(p.split("/")[0],10):null:null;t=!!m&&!!n;return _.x(A,My(a,g,d,e,h,t,l,q,null),2)}u=A.b;if(null==u)return A["return"](null);
a.j.has(c)?a.j.get(c).push(u):a.j.set(c,[u]);if(a.b.has(g))return A["return"](a.b.get(g));a.b.set(g,u);return A["return"](u)})},Ay=function(a,b){var c=fy(b,"CODECS","avc1.42E01E,mp4a.40.2").split(/\s*,\s*/),d=new Set,e=[];c=_.v(c);for(var f=c.next();!f.done;f=c.next()){f=f.value;var g=_.qi(f)[0];d.has(g)?a.a.debug("Ignoring duplicate codec"):(e.push(f),d.add(g))}return e},Jy=function(a,b,c,d){var e,f,g,h,l,m;return _.z(function(n){if(1==n.a){e=_.ok;f=gy(b,$x);if(a.b.has(f))return n["return"](a.b.get(f));
g=fy(b,Qx);h=null;d==e.VIDEO&&g&&"NONE"!=g&&(h=a.A.get(g));l=Cy(d,c);return _.x(n,My(a,f,l,d,_.Od,!1,null,null,h),2)}m=n.b;if(null==m)return n["return"](null);if(a.b.has(f))return n["return"](a.b.get(f));a.b.set(f,m);return n["return"](m)})},My=function(a,b,c,d,e,f,g,h,l){var m,n,p,q,t,u,A,D,G,H,L,T,wa,Ra,Zc,$c,ad,kb,Ja,Lb,Ma,dc,Ca,lb,Mb,Nb,tb,Xu,Kn,Yu;return _.z(function(bd){switch(bd.a){case 1:m=jy;n=m.Sc(a.m,b);if(a.g==qy&&a.u.has(n)){p=a.u.get(n);a.u["delete"](n);bd.a=2;break}return _.x(bd,ty(a,
n),3);case 3:t=bd.b,n=t.uri,p=oy(a.C,t.data,n);case 2:if(1!=p.type)throw new _.K(_.M,4,4017);u=[];p.b.forEach(function(Ln){Ln=m.pc(Ln.b,"EXT-X-KEY");u.push.apply(u,Ln)});A=!1;D=[];G=null;H=_.v(u);for(L=H.next();!L.done;L=H.next())T=L.value,wa=gy(T,"METHOD"),Ra=fy(T,"KEYFORMAT","identity"),"NONE"!=wa&&("AES-128"==wa?(Zc=fy(T,"IV",""),$c=m.Sc(a.m,gy(T,$x)),q={method:"AES-128",url:$c,iv:Zc?_.ei((Zc||"0x").slice(2)):null},a.v=!0):(A=!0,(kb=(ad=Ny[Ra])?ad(T):null)?(kb.keyIds.length&&(G=kb.keyIds[0]),D.push(kb)):
a.a.warn("Unsupported HLS KEYFORMAT",Ra)));if(A&&!D.length&&!a.v)throw new _.K(_.M,4,4026);Oy(a,p);return _.x(bd,Py(a,d,c,p),4);case 4:return Lb=Ja=bd.b,dc=(Ma=m.mb(p.a,Tx))?Number(Ma.value):0,_.x(bd,uy(a,b,p,dc,d,Lb,c,q),5);case 5:return Ca=bd.b,lb=Ca[0].startTime,Mb=Ca[Ca.length-1].endTime,Nb=Mb-lb,tb=new _.ln(Ca),Xu=Qy(p,q),Kn=void 0,d==_.k&&(Kn=_.Cd),Yu={id:a.W++,originalId:g,createSegmentIndex:Promise.resolve.bind(Promise),findSegmentPosition:tb.find.bind(tb),getSegmentReference:tb.get.bind(tb),
adjustSegmentDurations:tb.Pb.bind(tb),getDuration:tb.getDuration.bind(tb),initSegmentReference:Xu,presentationTimeOffset:0,mimeType:Lb,codecs:c,kind:Kn,encrypted:A,keyId:G,language:e,label:g,type:d,primary:f,trickModeVideo:null,emsgSchemeIdUris:null,frameRate:void 0,width:void 0,height:void 0,bandwidth:void 0,roles:[],channelsCount:h,closedCaptions:l,keyInfo:q},bd["return"]({stream:Yu,$a:tb,drmInfos:D,jd:b,Ff:n,Nd:lb,oj:Mb,duration:Nb})}})},Oy=function(a,b){var c=jy.mb(b.a,Ux),d=jy.mb(b.a,Sx);d=c&&
"VOD"==c.value||d;c=c&&"EVENT"==c.value&&!d;c=!d&&!c;d?vy(a,qy):(c?vy(a,Ry):vy(a,Sy),d=Ty(b.a,Wx),d=Number(d.value),a.I=Math.max(d,a.I),a.M=Math.min(d,a.M))},Qy=function(a,b){var c=jy.pc(a.a,"EXT-X-MAP");if(!c.length)return null;if(1<c.length)throw new _.K(_.M,4,4020);var d=c[0];c=gy(d,$x);var e=jy.Sc(a.c,c);c=0;var f=null;if(d=fy(d,"BYTERANGE"))c=d.split("@"),d=Number(c[0]),c=Number(c[1]),f=c+d-1;return new _.jn(function(){return[e]},c,f,b)},Uy=function(a,b,c,d,e){var f=b.b,g=b.a;b=Ty(f,"EXTINF").value.split(",");
b=d+Number(b[0]);var h=0,l=null;if(f=jy.mb(f,Rx))h=f.value.split("@"),f=Number(h[0]),h=h[1]?Number(h[1]):a.a+1,l=h+f-1;e&&!e.iv&&(e.iv=_.hi(new Uint8Array(12),new Uint8Array([c>>24&255,c>>16&255,c>>8&255,c&255])));return new _.kn(c,d,b,function(){return[g]},h,l,e)},yy=function(a){a.c&&(a.N.forEach(function(b){_.pn(a.c,b,0)}),a.N=[])},uy=function(a,b,c,d,e,f,g,h){var l,m,n,p,q,t,u,A,D,G,H,L;return _.z(function(T){if(1==T.a)return l=c.b,m=[],n=l[0].a,p=Uy(null,l[0],d,0,h||null),q=Qy(c,h||null),_.x(T,
Vy(a,b,q,p,e,f,g),2);t=T.b;a.a.debug("First segment",n.split("/").pop(),"starts at",t);for(u=0;u<l.length;++u)A=l[u],D=m[m.length-1],G=0==u?t:D.endTime,H=d+u,L=Uy(D,A,H,G,h||null),m.push(L);a.N.push(m);yy(a);return T["return"](m)})},Vy=function(a,b,c,d,e,f,g){var h;return _.z(function(l){if(1==l.a){if(null!==a.F){a.a.debug("Reusing cached start time for",e);l.a=2;return}h=a;return _.x(l,Wy(a,b,c,d,f,g),3)}2!=l.a&&(h.F=l.b,a.a.debug("Fetched start time for",e));return l["return"](a.F)})},Yy=function(a,
b){var c,d,e,f,g,h,l;return _.z(function(m){switch(m.a){case 1:return c=b.f(),d=_.pl(b.c(),b.b,b.b+2048-1,a.f.attemptParameters),d.type=_.Bn,e=_.pl(b.c(),b.b,b.a,a.f.attemptParameters),e.type=_.Bn,c&&(e.keyInfo=c),m.c=2,f=a.v?e:d,_.x(m,Xy(a,f),4);case 4:return g=m.b,m["return"](g);case 2:h=_.Ce(m);if(7001==h.code||a.v)throw h;a.a.warn("Unable to fetch a partial HLS segment! Falling back to a full segment request, which is expensive!  Your server should support Range requests and CORS preflights.",
d.uris[0]);return _.x(m,Xy(a,e),5);case 5:return l=m.b,m["return"](l)}})},Wy=function(a,b,c,d,e,f){var g,h,l,m,n,p,q,t,u,A,D;return _.z(function(G){switch(G.a){case 1:if(a.w){g=a.b.get(b);h=g.$a;if(l=h.get(d.position))return a.a.debug("Found segment start time in previous manifest"),G["return"](l.startTime);a.a.debug("Unable to find segment start time in previous manifest!")}a.a.debug("Fetching segment to find start time");if("audio/mpeg"==e)return G["return"](0);if("audio/aac"!=e){G.a=2;break}return _.x(G,
Yy(a,d),3);case 3:return m=G.b,n=_.N(m.data),by(n)?G["return"](Zy(n)):G["return"]($y(m.data));case 2:if(e!=_.Zd&&e!=_.Jb){G.a=4;break}p=[Yy(a,d)];c&&p.push(Yy(a,c));return _.x(G,Promise.all(p),5);case 5:return q=G.b,t=q[0],u=q[1]||q[0],G["return"](az(a,t.data,u.data));case 4:if(e!=_.Yd){G.a=6;break}return _.x(G,Yy(a,d),7);case 7:return A=G.b,G["return"]($y(A.data));case 6:D=bz;if(!D(e,f))return G["return"](0);throw new _.K(_.M,4,4030);}})},az=function(a,b,c){var d=0;(new _.ri).G("moov",_.si).G("trak",
_.si).G("mdia",_.si).T("mdhd",function(g){g.s.skip(0==g.version?8:16);d=_.Yh(g.s);g.Pa.stop()}).parse(c,!0);if(!d)throw a.a.error("Unable to find timescale in init segment!"),new _.K(_.M,4,4030);var e=0,f=!1;(new _.ri).G("moof",_.si).G("traf",_.si).T("tfdt",function(g){e=(0==g.version?_.Yh(g.s):_.$h(g.s))/d;f=!0;g.Pa.stop()}).parse(b,!0);if(!f)throw new _.K(_.M,4,4030);return e},$y=function(a){function b(){d.seek(e+188);f=_.Wh(d);71!=f&&(d.seek(e+192),f=_.Wh(d));71!=f&&(d.seek(e+204),f=_.Wh(d));71!=
f&&c();_.bi(d)}function c(){throw new _.K(_.M,4,4030);}for(var d=new _.Th(new DataView(a),!1),e=0,f=0;;)if(e=d.getPosition(),f=_.Wh(d),71!=f&&c(),a=_.Xh(d),8191===(a&8191))b();else if(a&16384)if(a=(_.Wh(d)&48)>>4,0!=a&&2!=a||c(),3==a&&(a=_.Wh(d),d.skip(a)),1!=_.Yh(d)>>8)b();else{d.skip(3);a=_.Wh(d)>>6;0!=a&&1!=a||c();0==_.Wh(d)&&c();a=_.Wh(d);var g=_.Xh(d),h=_.Xh(d);return(1073741824*((a&14)>>1)+((g&65534)<<14|(h&65534)>>1))/9E4}else b()},Zy=function(a){function b(l,m,n){for(var p="";m<n;m++)p+="%"+
("00"+l[m].toString(16)).slice(-2);return p}function c(l){return l[0]<<21|l[1]<<14|l[2]<<7|l[3]}function d(){throw new _.K(_.M,4,4030);}by(a)||d();var e=10;a[5]&64&&(e=e+4+c(a.subarray(10,14)));do{var f=c(a.subarray(e+4,e+8));1>f&&d();var g=String.fromCharCode(a[e],a[e+1],a[e+2],a[e+3]);if("PRIV"===g){g=a.subarray(e+10,e+f+10);for(var h=0;h<g.byteLength;h++)if(0===g[h]){if("com.apple.streaming.transportStreamTimestamp"===unescape(b(g,0,h)))return a=g.subarray(h+1),f=(a[3]&1)<<30|a[4]<<22|a[5]<<14|
a[6]<<6|a[7]>>>2,f*=4,f+=a[7]&3,Math.round(f/9E4);break}}by(a,e)||d();e+=10;e+=f}while(e<a.byteLength);return d()},By=function(a,b){for(var c=cz[a],d=0;d<c.length;d++)for(var e=0;e<b.length;e++)if(c[d].test(b[e].trim()))return b[e].trim();return a==_.k?"":null},Cy=function(a,b){if(1==b.length)return b[0];var c=By(a,b);if(null!=c)return c;throw new _.K(_.M,4,4025,{codecList:b});},Py=function(a,b,c,d){var e,f,g,h,l,m,n,p,q;return _.z(function(t){if(1==t.a){e=_.ok;f=d.b[0].a;g=new _.Sf(f);h=g.ha.split(".").pop();
l=dz[b];if(m=l[h])return t["return"](m);if(b==e.TEXT)return c&&"vtt"!=c?t["return"](ay):t["return"](_.Fd);n=_.hg([f],a.f.attemptParameters);n.method="HEAD";n.type=_.Bn;return _.x(t,Xy(a,n),2)}p=t.b;q=p.headers["content-type"];if(!q)throw new _.K(_.M,4,4021,h);return t["return"](q.split(";")[0])})},Ty=function(a,b){var c=jy.mb(a,b);if(!c)throw new _.K(_.M,4,4024,{missingTag:b});return c},ty=function(a,b){var c=_.hg([b],a.f.attemptParameters);c.type=1;return Xy(a,c)},bz=function(a,b){return MediaSource.isTypeSupported((a.split("/")[0]||
"")+'/mp4;codecs\x3d"'+b+'"')},py=function(a){var b,c;_.z(function(d){if(1==d.a){a.a.info(_.Ya);if(!a.h)return d["return"]();d.c=2;return _.x(d,a.update(),4)}if(2!=d.a)return b=a.R,a.l.P(b),_.Be(d,0);c=_.Ce(d);_.jf(c,1);a.h.onError(c);a.l.P(.1);_.y(d)})},vy=function(a,b){a.g=b;a.c&&(a.c.b=a.g==qy);a.g!=qy||a.l.stop()},Xy=function(a,b){if(!a.o)throw new _.K(_.M,7,7001);var c=a.h.networkingEngine.fetch(b);_.ql(a.o,c);return c.promise},ez=function(){},jy={pc:function(a,b){return a.filter(function(c){return c.name==
b})},Qe:function(a,b){return a.filter(function(c){return gy(c,"TYPE")===b})},mb:function(a,b){var c=jy.pc(a,b);return c.length?c[0]:null},lj:function(a,b,c){return a.filter(function(d){var e=d.getAttribute("TYPE");d=d.getAttribute(Xx);return e.value==b&&d.value==c})},Sc:function(a,b){return _.ni([a],[b])[0]},Hd:function(a){return/^#(?!EXT)/m.test(a)}};dy.prototype.toString=function(){function a(d){return d.name+"\x3d"+(isNaN(Number(d.value))?'"'+d.value+'"':d.value)}var b="#"+this.name,c=this.a?this.a.map(a):[];this.value&&c.unshift(this.value);0<c.length&&(b+=":"+c.join(","));return b};dy.prototype.getAttribute=function(a){var b=this.a.filter(function(c){return c.name==a});return b.length?b[0]:null};var ly=[Wx,Tx,"EXT-X-DISCONTINUITY-SEQUENCE",Ux,"EXT-X-MAP","EXT-X-I-FRAMES-ONLY",Sx],my=["EXTINF",Rx,"EXT-X-DISCONTINUITY","EXT-X-PROGRAM-DATE-TIME","EXT-X-KEY","EXT-X-DATERANGE"];_.r=ry.prototype;_.r.configure=function(a){this.f=a};_.r.start=function(a,b){var c=this,d,e;return _.z(function(f){if(1==f.a)return c.h=b,_.x(f,ty(c,a),2);if(3!=f.a)return d=f.b,c.m=d.uri,_.x(f,zy(c,d.data),3);e=c.R;0<e&&c.l.P(e);return f["return"](c.w)})};_.r.stop=function(){this.l&&(this.l.stop(),this.l=null);var a=[];this.o&&(a.push(this.o.destroy()),this.o=null);this.f=this.h=null;this.S.clear();this.b.clear();this.u.clear();this.w=null;this.j.clear();this.i.clear();return Promise.all(a)};
_.r.update=function(){var a=this,b,c,d;return _.z(function(e){if(1==e.a){if(a.g==qy)return e["return"]();b=[];a.F=null;c=Array.from(a.b.values());c.length?e=_.x(e,wy(a,c[0]),2):(e.a=2,e=void 0);return e}for(d=1;d<c.length;++d)b.push(wy(a,c[d]));return _.x(e,Promise.all(b),0)})};_.r.onExpirationUpdated=function(){};
var cz={audio:[/^vorbis$/,/^opus$/,/^flac$/,/^mp4a/,/^[ae]c-3$/],video:[/^avc/,/^hev/,/^hvc/,/^vp0?[89]/,/^av1$/],text:[/^vtt$/,/^wvtt/,/^stpp/]},dz={audio:{mp4:_.Jb,m4s:_.Jb,m4i:_.Jb,m4a:_.Jb,cmfa:_.Jb,ts:_.Yd,aac:"audio/aac"},video:{mp4:_.Zd,m4s:_.Zd,m4i:_.Zd,m4v:_.Zd,cmfv:_.Zd,ts:_.Yd},text:{mp4:ay,m4s:ay,m4i:ay,cmft:ay,vtt:_.Fd,ttml:_.Cb}},Ny={"urn:uuid:edef8ba9-79d6-4ace-a3c8-27dcd51d21ed":function(a){var b=gy(a,"METHOD"),c=["SAMPLE-AES","SAMPLE-AES-CTR","SAMPLE-AES-CENC"];if(!c.includes(b))return _.Te("Widevine in HLS is only supported with [",
c.join(", "),"], not",b),null;b=gy(a,$x);b=_.Af.parse(b);b=_.N(b.data);b=_.oi(_.lc,[{initDataType:_.Zb,initData:b}]);if(a=fy(a,"KEYID"))b.keyIds=[a.substr(2).toLowerCase()];return b}},qy="VOD",Sy="EVENT",Ry="LIVE",sy={VOD:qy,$i:Sy,LIVE:Ry};_.w(ez,_.wl);ez.prototype.ub=function(){_.Sn.ed("m3u8",ry);_.Sn.Ac(_.Ck,ry);_.Sn.Ac(_.Db,ry)};ez.prototype.cb=function(){_.Sn.Zd("m3u8");_.Sn.fd(_.Ck);_.Sn.fd(_.Db)};ez.prototype.id=function(){return"clpp.component.hls"};_.B("clpp.hls.HlsComponent",ez);};f.call(g, window);