import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var Br="A persistent DRM session already exists for: ",Cr="No DRM configuration.",Dr="clpp.persistent",Er=function(a){a.l=[a.c];a.h=0;a.g=0},Fr=function(a){var b=a.l.splice(0)[0];(b=a.c=a.c||b)?b.mf?a.a=a.h||a.g:void 0!=b.C&&a.g<b.C?(a.a=b.C,a.c=null):a.a=a.g:a.a=0},Gr=function(a,b){for(var c=[],d=_.u(a),e=d.next();!e.done;e=d.next())c.push(b(e.value));return c},Hr=function(a){a=a.c.keys();a=Gr(a,function(b){return b.sessionId});return Array.from(a)},Jr=function(a,b){a.B=Ir;a.D=[];a.w=!0;return _.nk(a,
b)},Lr=function(a,b,c,d,e,f){a.B=Kr;var g=new Map;g.set(b,{audioCapabilities:e,videoCapabilities:f,distinctiveIdentifier:_.bd,persistentState:_.sd,sessionTypes:[_.hd],label:b,drmInfos:[{keySystem:b,licenseServerUri:c,distinctiveIdentifierRequired:!1,persistentStateRequired:!0,audioRobustness:"",videoRobustness:"",serverCertificate:d,initData:null,keyIds:null}]});return _.tk(a,g)},Mr=function(a,b){var c,d,e;return _.A(function(f){if(1==f.a)return _.x(f,_.Ck(a,b),2);c=f.b;if(!c)return a.b.debug("Ignoring attempt to remove missing session",
b),f["return"]();d=[];(e=a.c.get(c))&&a.i&&(e.Oa=new _.nj,d.push(e.Oa));a.b.debug("Attempting to remove session",b);d.push(c.remove());return f["return"](Promise.all(d))})},Or=function(){this.a=null;this.c=Nr;this.b=new _.H(Dr)},Pr=function(a,b){var c=_.bl(a),d=_.Lj({drm:a});d.drm=a;var e=new _.jk({Pb:b,onError:function(){},fe:function(){},onExpirationUpdated:function(){},onEvent:function(){},getConfiguration:function(){return d}});e.f=c;return e},Qr=function(){},Rr=function(a){a=JSON.parse(a);var b=
JSON.parse(a.sessionIds),c=JSON.parse(a.audioCapabilities),d=JSON.parse(a.videoCapabilities),e=JSON.parse(a.serverCertificate),f=JSON.parse(a.drmConfig);return{sessionIds:b,keySystem:a.keySystem,licenseServerUri:decodeURIComponent(a.licenseServerUri),serverCertificate:new Uint8Array(e),audioCapabilities:c,videoCapabilities:d,drmConfig:f}},Tr=function(a,b,c){var d,e,f,g,h,l,m,n,p;return _.A(function(q){switch(q.a){case 1:d=Nr;e=Sr;if(!a)return e.debug(Cr),q["return"]();f=a.offlineId;return 0===f.length?
q["return"]():_.x(q,d.get(f),2);case 2:if(g=q.b)return e.debug(Br,f),q["return"]();h=Pr(a,c);_.Ce(q,3,4);return _.x(q,Jr(h,b),6);case 6:return _.x(q,_.wk(h),7);case 7:return _.x(q,_.xk(h),8);case 8:return l=h.getDrmInfo(),m=b.map(function(t){return{contentType:_.hg(t.video.mimeType,t.video.codecs),robustness:l.videoRobustness}}),n=Hr(h),g={sessionIds:n,keySystem:l.keySystem,licenseServerUri:l.licenseServerUri,serverCertificate:l.serverCertificate,audioCapabilities:[],videoCapabilities:m,drmConfig:a},
_.x(q,d.store(f,g),4);case 4:return Er(q),_.x(q,h.destroy(),10);case 10:Fr(q);break;case 3:throw p=_.Ee(q),e.error("Error while persisting DRM session"),new _.J(1,6,6200,null,p);}})},Ir=1,Kr=2;_.w(Or,_.nl);_.r=Or.prototype;_.r.rb=function(a){this.a=a};_.r.ib=function(){this.a=null};_.r.release=function(){};_.r.wc=function(){this.c=Nr};_.r.id=function(){return _.ec};
_.r.kj=function(a,b,c){var d=this,e;return _.A(function(f){if(1==f.a){if(!a)return d.b.debug("No DRM configuration found for loaded source."),f["return"]();_.Ce(f,2);return _.x(f,Tr(a,b,c),4)}if(2!=f.a)return d.a.trigger(new _.O(_.tc,{offlineId:a.offlineId})),_.De(f,0);e=_.Ee(f);d.a.onError(e);_.y(f)})};
_.r.$h=function(a){var b=this,c;return _.A(function(d){if(1==d.a)return _.Ce(d,2),_.x(d,b.c.get(a),4);if(2!=d.a){if(c=d.b)return d["return"](c.sessionIds);b.b.debug("No offline session found for "+a);return d["return"]([])}_.Ee(d);b.b.warn("Error while loading session info from storage");return d["return"]([])})};_.B("clpp.persistent.PersistentLicenseComponent",Or);_.r=Qr.prototype;
_.r.store=function(a,b){var c;return _.A(function(d){var e=JSON.stringify(b.sessionIds),f=Array.from(b.serverCertificate);f=JSON.stringify(f);var g=JSON.stringify(b.audioCapabilities),h=JSON.stringify(b.videoCapabilities);c=JSON.stringify({sessionIds:e,keySystem:b.keySystem,licenseServerUri:encodeURIComponent(b.licenseServerUri),serverCertificate:f,audioCapabilities:g,videoCapabilities:h,drmConfig:JSON.stringify(b.drmConfig)});window.localStorage.setItem(encodeURIComponent(a),btoa(c));_.y(d)})};
_.r.get=function(a){var b;return _.A(function(c){return(b=window.localStorage.getItem(encodeURIComponent(a)))?c["return"](Rr(atob(b))):c["return"](null)})};_.r["delete"]=function(a){return _.A(function(b){window.localStorage.removeItem(encodeURIComponent(a));_.y(b)})};_.r.clear=function(){return _.A(function(a){window.localStorage.clear();_.y(a)})};_.r.getName=function(){return"clpp.persistent.SimpleSessionStorage"};_.B("clpp.persistent.useStorage",function(a){var b=["store","get","delete","clear","getName"];var c=[];_.C.I(a)||(_.C.Mb(a.store)||c.push("store"),_.C.Mb(a.get)||c.push("get"),_.C.Mb(a["delete"])||c.push("delete"),_.C.Mb(a.clear)||c.push("clear"),_.C.Mb(a.getName)||c.push("getName"),b=c);if(0<b.length)throw Sr.warn("Invalid session storage implementation"),new _.J(1,6,6202,{missingMethods:b});Nr=a});
_.B("clpp.persistent.fetchLicense",function(a,b,c){for(var d=[],e=2;e<arguments.length;++e)d[e-2]=arguments[e];var f,g,h,l,m,n,p,q,t,v,z,F,E,D,L,R,oa,Da,Ua;return _.A(function(Ka){switch(Ka.a){case 1:f=Nr;g=Sr;h=function(Ob,xb){return new _.J(1,6,6200,Ob,xb)};l=_.yl(a).shift();if(!l)throw h("No source specified.");if(!b)throw h(Cr);m=b.offlineId;if(typeof m!==_.Fd||!m.length)throw h("Missing offline id.");return _.x(Ka,f.get(m),2);case 2:if(n=Ka.b)return g.debug(Br,m),Ka["return"]();p=_.Lj();q=new _.Fj;
t=[];v=_.u(d);for(z=v.next();!z.done;z=v.next())F=z.value,E=new F,_.jl(E.id())||(E.rb(null),_.ll(E),t.push(E));D=null;_.Ce(Ka,3,4);return _.x(Ka,_.Do.create(l.url,q,p.manifest.attemptParameters,l.type),6);case 6:return D=Ka.b,D.configure(p.manifest),_.x(Ka,D.start(l.url,{networkingEngine:q,filterAllPeriods:function(){},filterNewPeriod:function(){},onTimelineCueAdded:function(){},onEvent:function(){},onError:function(){}}),7);case 7:L=Ka.b;if(!L.periods.length)throw h(null,new _.J(_.K,4,4014));R=_.Lm(L.periods);
return _.x(Ka,Tr(b,R,q),4);case 4:for(Er(Ka);t.length;)oa=t.shift(),oa.ib(),_.il["delete"](oa.id());Da=[];D&&Da.push(D.stop());Da.push(q.destroy());return _.x(Ka,Promise.all(Da),9);case 9:Fr(Ka);break;case 3:Ua=_.Ee(Ka);if(Ua instanceof _.J&&6200===Ua.code)throw Ua;throw h(null,Ua);}})});
_.B("clpp.persistent.removeLicense",function(a){var b,c,d,e,f,g,h;return _.A(function(l){switch(l.a){case 1:b=Nr;c=Sr;if(!_.C.aa(a)||0===a.length)return c.warn("Invalid offlineId"),l["return"]();e=d=null;_.Ce(l,2,3);return _.x(l,b.get(a),5);case 5:f=l.b;if(!f)return c.debug("No persistent DRM session found"),l["return"]();f.drmConfig.delayLicenseRequestUntilPlayed=!0;e=new _.Fj;d=Pr(f.drmConfig,e);return _.x(l,Lr(d,f.keySystem,f.licenseServerUri,f.serverCertificate,f.audioCapabilities,f.videoCapabilities),
6);case 6:return _.x(l,_.wk(d),7);case 7:return _.x(l,Promise.all(f.sessionIds.map(function(m){return _.A(function(n){if(1==n.a)return _.x(n,Mr(d,m),2);c.debug("sucessfully removed session with id",m);_.y(n)})})),8);case 8:return _.x(l,b["delete"](a),3);case 3:return Er(l),g=[],d&&g.push(d.destroy()),e&&g.push(e.destroy()),_.x(l,Promise.all(g),10);case 10:Fr(l);break;case 2:throw h=_.Ee(l),c.error("Failed to remove session"),new _.J(1,6,6201,null,h);}})});var Nr=new Qr,Sr=new _.H(Dr);};f.call(g, window);