import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var Bo="Full MP4 box must have flags defined",Co="clpp.smooth.SmoothMP4Processor",Do="codecPrivateData",Eo=function(a,b){var c=Math.floor(b/Math.pow(2,32)),d=b-c*Math.pow(2,32);_.P(a,c);_.P(a,d)},Fo=function(a,b){try{a.b.setUint8(a.a,b),a.a+=1}catch(c){_.Rh()}},Go=function(a,b){Fo(a,b>>16&255);Fo(a,b>>8&255);Fo(a,b&255)},Ho=function(a,b){try{a.b.setUint16(a.a,b,a.c),a.a+=2}catch(c){_.Rh()}},Io=function(a,b){try{a.b.setInt32(a.a,b,a.c),a.a+=4}catch(c){_.Rh()}},Jo=function(a,b){try{a.b.setInt16(a.a,
b,a.c),a.a+=2}catch(c){_.Rh()}},Ko=function(a,b){if(void 0!=b){for(var c=new Uint8Array(b),d=Math.min(a.length,b),e=0;e<d;++e)c[e]=a.charCodeAt(e);for(;e<b;e++)c[e]=0;return c}c=new Uint8Array(a.length);for(d=0;d<a.length;++d)c[d]=a.charCodeAt(d);return c},Mo=function(a){this.a=a;this.b=Lo(this)},Lo=function(a){for(var b=0,c=0;c<a.a.length;c++)b+=a.a[c].a();return new _.Qh(b)},W=function(a){this.type=a;this.size=this.start=0;this.parent=null;this.j=!1;this.entries=[];this.b=[]},No=function(a,b){b=
void 0===b?[]:b;for(var c=0;c<b.length;c++)a.b.push(b[c]),b[c].parent=a;return a},X=function(a,b,c){W.call(this,a);this.version=b;this.flags=c},Oo=function(a,b,c){W.call(this,a);this.c=b;this.offset=c},Po=function(a,b,c,d,e){X.call(this,a,b,c);this.c=d;this.offset=e},Qo=function(a,b,c){W.call(this,"ftyp");this.f=a;this.df=b;this.c=c},Ro=function(){W.call(this,"moov")},So=function(){W.call(this,"trak")},To=function(a,b,c){X.call(this,"mvhd",1,0);this.timescale=a;this.duration=b;this.volume=256;this.f=
c+1;this.c=[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0]},Uo=function(){W.call(this,"mvex")},Vo=function(a){X.call(this,"trex",0,0);this.c=a},Wo=function(a,b,c,d,e){X.call(this,"tkhd",1,7);this.f=a;this.duration=b;this.timescale=c;this.width=d;this.height=e;this.volume=1;this.c=[0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,64,0,0,0]},Xo=function(a,b){X.call(this,"mdhd",1,0);this.timescale=a;this.duration=b;this.language=21956},Yo=function(a){X.call(this,
"hdlr",0,0);this.c=a},Zo=function(){X.call(this,"vmhd",0,1);this.c=new Uint8Array([0,0,0,0,0,0])},$o=function(a){W.call(this,a);this.j=!0},ap=function(a){$o.call(this,a);this.height=this.width=0},bp=function(a,b,c,d){$o.call(this,a);this.channelCount=b;this.sampleSize=c;this.sampleRate=d},cp=function(a,b){ap.call(this,"avc1");this.width=a;this.height=b},dp=function(a,b){cp.call(this,a,b);this.type="encv"},ep=function(a,b,c){bp.call(this,"mp4a",a,b,c)},fp=function(a,b,c){ep.call(this,a,b,c);this.type=
"enca"},gp=function(a,b){W.call(this,"avcC");this.ka=a;this.Ya=b;this.version=1;this.f=this.ka[0][1];this.g=this.ka[0][2];this.c=this.ka[0][3]},hp=function(a){X.call(this,"esds",0,0);this.Ra=a},ip=function(a){a=void 0===a?"":a;X.call(this,"url ",0,1);this.location=a},jp=function(){X.call(this,"dref",0,0)},kp=function(){W.call(this,"stbl")},lp=function(){X.call(this,"stsd",0,0)},mp=function(){X.call(this,"stts",0,0)},np=function(){X.call(this,"stsc",0,0)},op=function(){X.call(this,"stco",0,0)},pp=
function(){X.call(this,"stsz",0,0)},qp=function(){X.call(this,"smhd",0,0)},rp=function(){W.call(this,"dinf")},sp=function(){W.call(this,"minf")},tp=function(){W.call(this,"mdia")},up=function(a,b){X.call(this,"tfdt",a,0);this.c=b},vp=function(){X.call(this,"mfhd",0,0);this.c=0},wp=function(a,b){X.call(this,"trun",a,b);this.h=this.g=this.c=0;this.i=[];this.sampleSize=[];this.l=[];this.f=[]},xp=function(a,b){X.call(this,"tfhd",a,b);this.c=255;this.h=this.i=this.g=this.l=this.f=0},yp=function(){W.call(this,
"traf")},zp=function(){W.call(this,"moof")},Ap=function(){W.call(this,_.Rc);this.c=new Uint8Array(0)},Bp=function(){X.call(this,"tenc",0,0);this.c=1;this.f=8;this.h="";this.g=[]},Cp=function(a,b){X.call(this,"schm",0,0);this.c=a;this.f=b;this.Za=""},Dp=function(a){W.call(this,"frma");this.c=a},Ep=function(){X.call(this,"saio",0,0);this.offset=[0]},Fp=function(a,b,c){X.call(this,"saiz",0,0);this.c=a;this.g=b;this.f=c},Gp=function(a,b){X.call(this,"senc",a,b);this.f=0;this.g=8;this.c=[]},Hp=function(a,
b){var c=a.exec(b);return null==c||""==c[0]?null:(Number(c[4])||0)/1E3+(Number(c[3])||0)+60*(Number(c[2])||0)+3600*(Number(c[1])||0)},Op=function(a,b,c){var d=null;if(Ip.test(a)){a=Ip.exec(a);d=Number(a[1]);var e=Number(a[2]),f=Number(a[3]),g=Number(a[4]);g+=(Number(a[5])||0)/c.b;f+=g/c.frameRate;d=f+60*e+3600*d}else Jp.test(a)?d=Hp(Jp,a):Kp.test(a)?d=Hp(Kp,a):Lp.test(a)?(a=Lp.exec(a),d=Number(a[1])/c.frameRate):Mp.test(a)?(a=Mp.exec(a),d=Number(a[1])/c.a):Np.test(a)&&(d=Hp(Np,a));d+=b;b=Math.floor(d/
3600);c=Math.floor((d-3600*b)/60);a=Math.floor(d-3600*b-60*c);d-=a;10>b&&(b="0"+b);10>c&&(c="0"+c);10>a&&(a="0"+a);0===d?d="000":d=Math.round(1E3*d);return b+":"+c+":"+a+"."+d},Pp=function(a,b,c,d){this.frameRate=Number(a)||30;this.b=Number(b)||1;this.a=Number(d);0==this.a&&(this.a=a?this.frameRate*this.b:1);c&&(a=/^(\d+) (\d+)$/g.exec(c))&&(this.frameRate*=parseInt(a[1],10)/parseInt(a[2],10))},Qp=function(a,b,c){return{keySystem:a,licenseServerUri:"",distinctiveIdentifierRequired:!1,persistentStateRequired:!1,
audioRobustness:"",videoRobustness:"",serverCertificate:null,initData:[b],keyIds:c}},Rp=function(a){var b=_.Ig();a="ie"===b.browser||"edge"===b.browser?a.Bd(_.kc):a.Bd(_.lc);null===a&&(_.C(Co,"Could not get PSSH box!"),a={initData:new Uint8Array(0),initDataType:_.Zb,keyId:""});return a},Sp=function(a,b,c){var d=Rp(c);c=new W("xxxx");a.type===_.Xd?c=new dp(a.width,a.height):c=new fp(a.channelCount,a.sampleSize,a.Bc);a=new Bp;a.c=1;a.f=8;a.h=d.keyId||"00000000000000000000000000000000";a=No(new W("schi"),
[a]);b=No(new W("sinf"),[new Dp(b),new Cp(_.Zb,65536),a]);No(c,[b]);return c},Tp=function(a,b){var c=b.vc(),d=new To(a.timescale,a.duration,a.id),e=No(new Uo,[new Vo(a.id)]),f=new Wo(a.id,a.duration,a.timescale,a.width,a.height),g=new Xo(a.timescale,a.duration),h=new Yo(a.type),l=null,m=new jp;m.entries=[new ip];var n=new lp;switch(a.type){case _.Xd:var p=new gp(a.ka,a.Ya);c?(l=Sp(a,"avc1",b),No(l,[p]),n.entries=[l]):(l=No(new cp(a.width,a.height),[p]),n.entries=[l]);l=new Zo;break;case _.Ib:p=new hp(a.Ra),
c?(l=Sp(a,"mp4a",b),No(l,[p]),n.entries=[l]):(l=No(new ep(a.channelCount,a.sampleSize,a.Bc),[p]),n.entries=[l]),l=new qp}n=No(new kp,[n,new mp,new np,new pp,new op]);m=No(new rp,[m]);m=No(new sp,[l,m,n]);g=No(new tp,[g,h,m]);f=No(new So,[f,g]);d=No(new Ro,[d,f,e]);e=new Qo("dash",0,["iso6","mp41","avc1"]);c&&(c=Rp(b).initData,No(d,[new Oo("pssh",c,8)]));c=new Mo([e,d]);return _.N(c.write())},Vp=function(a,b){var c,d,e,f,g,h;(new _.ri).G("moof",_.si).T("mfhd",function(m){var n=new vp;n.c=_.Yh(m.s);
c=n}).G("traf",_.si).T("tfhd",function(m){var n=m.s.ea();if(null===m.flags)throw new _.K(_.M,3,3019,Bo);var p=new xp(m.version||0,m.flags||0);p.c=_.Yh(m.s);0<n-m.s.getPosition()&&m.flags&1&&(p.f=_.$h(m.s));0<n-m.s.getPosition()&&m.flags&2&&(p.l=_.Yh(m.s));0<n-m.s.getPosition()&&m.flags&8&&(p.g=_.Yh(m.s));0<n-m.s.getPosition()&&m.flags&16&&(p.i=_.Yh(m.s));0<n-m.s.getPosition()&&m.flags&32&&(p.h=_.Yh(m.s));d=p}).T("trun",function(m){var n=m.s.ea();if(null===m.flags)throw new _.K(_.M,3,3019,Bo);var p=
new wp(m.version||0,m.flags||0);p.c=_.Yh(m.s);0<n-m.s.getPosition()&&m.flags&1&&(p.g=_.Zh(m.s));0<n-m.s.getPosition()&&m.flags&4&&(p.h=_.Yh(m.s));if(0<n-m.s.getPosition())for(n=0;n<p.c;n++)m.flags&256&&p.i.push(_.Yh(m.s)),m.flags&512&&p.sampleSize.push(_.Yh(m.s)),m.flags&1024&&p.l.push(_.Yh(m.s)),m.flags&2048&&(0===m.version?p.f.push(_.Yh(m.s)):p.f.push(_.Zh(m.s)));e=p}).T("sdtp",function(m){var n=_.ai(m.s,m.s.ea());f=new Po("sdtp",m.version||0,m.flags||0,n,0)}).G("uuid",function(m){if(_.ai(m.s,16).toString()===
Up.toString()){var n=_.Yh(m.s);m.version=n>>>24;m.flags=n&16777215;n=new Gp(m.version,m.flags);n.f=_.Yh(m.s);m.flags&1&&(n.g=_.Wh(m.s));for(var p=0;p<n.f;p++){var q={Ze:_.ai(m.s,8),dc:0,ae:[]};if(m.flags&2){q.dc=_.Xh(m.s);for(var t=0;t<q.dc;t++){var u={me:0,ne:0};u.me=_.Xh(m.s);u.ne=_.Yh(m.s);q.ae.push(u)}}n.c.push(q)}g=n}}).G(_.Rc,function(m){var n=new Ap;0<m.s.ea()?n.c=_.ai(m.s,m.s.ea()):(_.C(Co,"mdat box is empty!"),n.c=new Uint8Array(0));h=n}).parse(a,!1);if(!l&&!h)return null;b.vc();var l=No(new yp,
[d,e]);f&&No(l,[f]);b.vc()&&No(l,[g]);l=No(new zp,[c,l]);return new Mo([l,h])},Wp=function(a,b,c){var d=c.vc(),e=a.request.startTime,f=parseInt(e*b,10);b=a.data||new ArrayBuffer(0);var g=Vp(b,c);if(null===g)return a.request.contentType===_.k?a.data:g;c=g.get(_.Rc);if(a.request.contentType===_.k){d=c.c.buffer;if(e){c=_.pf(d);a=new DOMParser;d=null;try{d=a.parseFromString(c,_.Gd)}catch(G){throw G;}if(d&&"tt"===d.documentElement.tagName.toLowerCase())var h=d.documentElement;if(h)for(c=new Pp(h.getAttribute("ttp:frameRate"),
h.getAttribute("ttp:subFrameRate"),h.getAttribute("ttp:frameRateMultiplier"),h.getAttribute("ttp:tickRate")),h=h.getElementsByTagName("body")[0].getElementsByTagName("p"),a=0,b=h.length;a<b;a++){f=h[a];g=c;for(var l=["begin",_.xc],m=0,n=l.length;m<n;m++){b:{var p=f;var q=l[m];var t=new RegExp("\\w+:"+q),u=0;if(p.hasAttribute(q))p=p.getAttribute(q);else{var A=p.attributes;for(q=A.length;u<q;u++){var D=A[u].name;if(D=D.match(t)){p=p.getAttribute(D[0]);break b}}p=null}}f.setAttribute(l[m],Op(p||"",e,
g))}}c=(new XMLSerializer).serializeToString(d);e=_.uf(c).buffer}else e=d;return e}h=new zp;a=g.get("mfhd");b=new yp;l=g.get("tfhd");m=new up(1,f);f=g.get("trun");n=g.get("sdtp");e=g.get("senc");l.c=1;l.flags&=16777214;l.flags|=131072;No(b,[l,m,f]);n&&No(b,[n]);if(d){g=0;l=[];if(e.flags&2)for(l=[],m=0;m<e.f;m++)l.push(10+6*e.c[m].dc);else g=8;No(b,[e,new Ep,new Fp(g,l,e.f)])}No(h,[a,b]);f.flags|=1;f.g=h.a()+8;c=new Mo([h,c]);h=c.write();d&&(d=c.get("saio"),c=c.b,d.offset[0]=e.start+16,c.seek(d.start),
d.write(c),h=c.buffer);return h},Xp=function(a){var b=a.split("/");return b[b.length-1].toLowerCase().match("manifest(\\(.+\\))?")?a:a+"/Manifest"},Yp=function(a,b,c,d){c=b.Ue[c];b=b.Wi;a=a.replace("Manifest","");b=b.replace("{bitrate}",String(d.bitrate)).replace("{Bitrate}",String(d.bitrate)).replace("{start time}",String(c.t)).replace("{start_time}",String(c.t));return _.ni([a],[b])[0]},Zp=function(a,b,c){var d=c.Rc.split("00000001");a={id:1,type:c.type,duration:a/b,timescale:b,ka:null,Ya:null,
width:NaN,height:NaN,Ra:null,Bc:NaN,sampleSize:NaN,channelCount:NaN};switch(c.type){case _.Xd:a.ka=[_.ei(d[1])];a.Ya=[_.ei(d[2])];a.width=c.maxWidth;a.height=c.maxHeight;break;case _.Ib:a.Ra=_.ei(c.Rc),a.sampleSize=c.Tf||16,a.Bc=c.Bc,a.channelCount=c.pe}return a},$p=function(a,b){return a.filter(function(c){return c.type===b})},bq=function(){this.f=this.g=this.j=this.a=null;this.C=1;this.I=0;this.i="";this.m=this.c=null;this.b=new _.E("clpp.smooth.SmoothParser");this.v=!1;this.h=this.o=null;this.F=
aq;this.u=0;this.w=Infinity;this.l=[];this.A=this.Ni.bind(this)},cq=function(a){var b=_.hg(a.i);b.timeout=a.j.attemptParameters.timeout;b.maxAttempts=a.j.attemptParameters.maxAttempts;b.baseDelay=a.j.attemptParameters.baseDelay;b.backoffFactor=a.j.attemptParameters.backoffFactor;b.fuzzFactor=a.j.attemptParameters.fuzzFactor;b.type=1;return a.a.networkingEngine.fetch(b).promise},kq=function(a,b){var c=null;try{var d=new DOMParser;try{var e=_.pf(b);var f=d.parseFromString(e.trim(),_.Gd)}catch(t){throw t;
}if(f&&f.documentElement.tagName==_.Ua)var g=f.documentElement;c=g&&0<g.getElementsByTagName(_.gd).length?null:g}catch(t){}if(!c)throw a.b.error("Unable to parse manifest"),new _.K(_.M,4,4033,a.i);d=+dq(a,c,"MajorVersion");g=+dq(a,c,"MinorVersion");f=+c.getAttribute("TimeScale")||1E7;e=+dq(a,c,"Duration");var h="TRUE"===c.getAttribute("IsLive"),l=+c.getAttribute("LookAheadCount"),m=+c.getAttribute("DVRWindowLength")||Infinity,n=_.Q.J(c,"Protection")[0];if(!1===/^[2].[0-2]$/.test(""+d+"."+g))throw a.b.error("Smooth Streaming version must be 2.0, 2.1 or 2.2"),
new _.K(_.M,4,4036,a.i);h?(eq(a,fq),a.o=1E3,e=Infinity):eq(a,aq);a.c={startTime:0,delay:0,duration:e/f,Me:m/f,wc:0};if(n){var p=[];n=_.Q.J(n,"ProtectionHeader")[0];n=_.di(_.Q.lb(n)||"");var q=_.ij(n).a;p.push(Qp(_.lc,{initData:_.bj(_.ej(q)),initDataType:_.Zb,keyId:q},[q]));p.push(Qp(_.kc,{initData:_.bj(_.ij(n)),initDataType:_.Zb,keyId:q},[q]));a.l=p}p=[];c=_.Q.J(c,"StreamIndex");if(!c.length)throw a.b.error("No streams found!"),new _.K(_.M,4,4034,a.i);for(n=0;n<c.length;n++)q=gq(a,c[n]),p.push(q);
c={nj:d,df:g,timescale:f,duration:e,isLive:h,mj:l,Me:m,Fd:!1,streams:p};if(a.g&&a.f){for(d=0;d<a.f.streams.length;d++)for(g=0;g<a.f.streams[d].tracks.length;g++)f=a.f.streams[d].tracks[g],e=c.streams[d].tracks[g],f.type!==e.type?f=!1:(h=[],f.type===_.Xd?h=["maxWidth","maxHeight","bitrate",Do,"fourCC"]:f.type===_.Ib&&(h=["bitrate",Do,"channels","bitsPerSample","samplingRate","fourCC"]),f=_.J.ua(f,e,h,["id","segmentIndex"])),f||a.b.warn("The current stream is updated with a stream that seems to have different base properties!"),
f=c.streams[d],f=hq(a,a.f.timescale,f,f.tracks[g]),a.f.streams[d].tracks[g].$a.Va(f);return Promise.resolve()}e=c.timescale;h=c.duration;g=$p(c.streams,_.Ib);f=$p(c.streams,_.Xd);l=$p(c.streams,_.k);d=[];g=iq(a,h,e,g);f=iq(a,h,e,f);e=iq(a,h,e,l);g.length||(g=[null]);f.length||(f=[null]);for(h=0;h<f.length;h++)for(l=0;l<g.length;l++)d.push(jq(a,f[h],g[l]));d={startTime:0,variants:d,textStreams:e,thumbStreams:[]};g=a.c.startTime;f=a.c.delay;e=Math.min(a.c.duration||Infinity,a.w);h=a.mc();l=a.c.Me;m=
a.c.wc;p=a.u;h&&(e=Infinity,g=Date.now()/1E3-m,a.c.startTime=g);a.m=new _.nn(g,f,!0);a.m.b=!h;a.m.bb(e);_.qn(a.m,p);a.m.Fb=l;a.a.filterAllPeriods([d]);a.g={presentationTimeline:a.m,periods:[d],offlineSessionIds:[],minBufferTime:0};Promise.resolve();a.v||(a.a.networkingEngine.qd(a.A),a.v=!0);a.f=c;return Promise.resolve()},gq=function(a,b){var c=dq(a,b,"Type"),d=+b.getAttribute("Chunks"),e=b.getAttribute("Subtype"),f=_.vl(b.getAttribute("Language")||_.Od),g=b.getAttribute("Name")||"",h=+b.getAttribute(_.ya),
l=+b.getAttribute(_.xa),m=dq(a,b,"Url"),n=lq(a,b,c),p=mq(a,b,d);n.sort(function(q,t){return q.bitrate-t.bitrate});return{type:c,fj:d,Si:e,language:f,name:g,maxWidth:h,maxHeight:l,Wi:m,tracks:n,Ue:p}},lq=function(a,b,c){var d=[];b=_.Q.J(b,_.Ka);for(var e=0;e<b.length;e++){var f=a;var g=b[e],h=c,l=+g.getAttribute("Index"),m=+dq(f,g,"Bitrate"),n=NaN,p=NaN,q=NaN,t=NaN,u=NaN,A=NaN,D=NaN,G=g.getAttribute("FourCC");switch(h){case _.Xd:n=+dq(f,g,_.xa);p=+dq(f,g,_.ya);break;case _.Ib:t=+g.getAttribute("Channels")||
2,q=+dq(f,g,"SamplingRate"),A=+dq(f,g,"AudioTag"),u=+dq(f,g,"BitsPerSample"),D=+dq(f,g,"PacketSize")}g=String(g.getAttribute("CodecPrivateData"));if(h===_.Ib&&!g){var H=t;var L={96E3:0,88200:1,64E3:2,48E3:3,44100:4,32E3:5,24E3:6,22050:7,16E3:8,12E3:9,11025:10,8E3:11,7350:12},T=L[q];"AACH"===G?(g=new Uint8Array(4),L=L[2*q],g[0]=40|T>>1,g[1]=T<<7|H<<3|L>>1,g[2]=L<<7|8,g[3]=0,H=new Uint16Array(2),H[0]=(g[0]<<8)+g[1],H[1]=(g[2]<<8)+g[3],g=H[0].toString(16)+H[1].toString(16)):(g=new Uint8Array(2),g[0]=
16|T>>1,g[1]=T<<7|H<<3,H=new Uint16Array(1),H[0]=(g[0]<<8)+g[1],g=H[0].toString(16));g=g.toUpperCase()}f={id:f.I++,type:h,index:l,bitrate:m,Rc:g,maxHeight:n,maxWidth:p,Bc:q,pe:t,ej:A,Tf:u,pj:D,xh:G,$a:null};d.push(f)}return d},mq=function(a,b,c){var d=[];b=_.Q.J(b,"c");for(var e=0;e<b.length;e++){var f=b[e],g=parseInt(f.getAttribute("t"),10),h=parseInt(f.getAttribute("d"),10);f=parseInt(f.getAttribute("r"),10);var l=0;if(isNaN(g)&&isNaN(h))throw a.b.error("Either one or both FragmentDuration and FragmentTime field MUST be present in StreamFragmentElement"),
new _.K(_.M,4,4037,a.i);0===e&&isNaN(g)&&(l=g=0);if(0<e){var m=d[d.length-1];l=m.n+1;m.d||(m.d=g-m.t);g||(g=m.t+m.d);h||(h=g-m.t)}d.push({n:l,d:h,t:g});if(f)for(f--,m=0;m<f;m++)h=d[d.length-1],l=h.n+1,g=h.t+h.d,h=h.d,d.push({n:l,d:h,t:g})}a.mc()||d.length===c||a.b.warn("Number of fragments ("+c+") differs from number of chunks ("+d.length+").");return d},iq=function(a,b,c,d){for(var e=[],f={Nb:0};f.Nb<d.length;f={Nb:f.Nb},f.Nb++){var g=d[f.Nb].tracks.map(function(h){return function(l){var m=d[h.Nb],
n=hq(a,c,m,l),p=new _.ln(n),q=null;m.type!==_.k&&(q=nq(a,b,c,l));l.$a=p;n=a.C++;var t=Promise.resolve.bind(Promise),u=p.find.bind(p),A=p.get.bind(p),D=p.Pb.bind(p);p=p.getDuration.bind(p);var G=oq[m.type],H="";switch(m.type){case _.Xd:H=l.Rc;var L=/00000001[0-9]7/.exec(H);H="avc1."+(L&&L[0]?H.substr(H.indexOf(L[0])+10,6):"42c00c");a.b.debug("VIDEO CODECS: ",H);break;case _.Ib:H=l.Rc,L=2,"AACH"===l.xh?L=5:H&&(L=(parseInt(H.substr(0,2),16)&248)>>3),H="mp4a.40."+L,a.b.debug("AUDIO CODECS: ",H)}L=m.type===
_.k?pq[m.Si]:void 0;return{id:n,originalId:null,rj:null,createSegmentIndex:t,findSegmentPosition:u,getSegmentReference:A,adjustSegmentDurations:D,getDuration:p,initSegmentReference:q,presentationTimeOffset:0,mimeType:G,codecs:H,frameRate:void 0,bandwidth:l.bitrate,width:l.maxWidth||void 0,height:l.maxHeight||void 0,kind:L,encrypted:a.Kd(),keyId:null,language:m.language,label:m.name,type:m.type,primary:!1,trickModeVideo:null,emsgSchemeIdUris:null,roles:[],channelsCount:l.pe||null,closedCaptions:null}}}(f));
e=e.concat(g)}return e},hq=function(a,b,c,d){var e=0,f=[];c.Ue.forEach(function(h,l){var m=h.d/b,n;0===l?n=h.t/b:n=f[l-1].endTime;var p=n+m,q=Yp(a.i,c,l,d);a.u=Math.max(a.u,m);f.push(new _.kn(l,n,p,function(){return[q]},0,null,null,!0));e+=m});if(c.type===_.Xd||c.type===_.Ib){var g=f[f.length-1];a.w=Math.min(a.w,e);0===a.c.wc?a.c.wc=g.endTime:a.c.wc=Math.min(a.c.wc,g.endTime)}return f},nq=function(a,b,c,d){b=Zp(b,c,d);c={isLive:a.mc.bind(a),vc:a.Kd.bind(a),Eh:function(){return 1},Bd:a.We.bind(a)};
d=new Uint8Array(0);try{d=Tp(b,c)}catch(f){throw a.b.error("Failed to generate initialization segment."),new _.K(_.M,3,4035,f);}var e="data:text/plain;base64,"+_.ci(d);return new _.jn(function(){return[e]},0,null,null,!0)},jq=function(a,b,c){var d=(c?c.bandwidth:0)+(b?b.bandwidth:0),e=c?c.language:_.Od;return c||b?{id:a.C++,language:e,primary:!1,audio:c,video:b,bandwidth:d,drmInfos:a.l,allowedByApplication:!0,allowedByKeySystem:!0}:null},dq=function(a,b,c){if(b=b.getAttribute(c))return b;a.b.error("required attribute not provided: "+
c);throw new _.K(_.M,4,4038,a.i,c);},qq=function(a,b){null!=a.o&&null!=b&&(a.h=window.setTimeout(a.Wg.bind(a),b))},eq=function(a,b){var c=b===aq;a.g&&a.g.presentationTimeline&&(a.g.presentationTimeline.b=c);c&&null!=a.h&&(window.clearTimeout(a.h),a.h=null,a.o=null);a.F=b},rq=function(){};Mo.prototype.get=function(a){for(var b=0;b<this.a.length;b++){var c=this.a[b].get(a);if(c)return c}return null};
Mo.prototype.write=function(){this.b=Lo(this);for(var a=0;a<this.a.length;a++)this.a[a].write(this.b);return this.b.buffer};W.prototype.get=function(a){if(this.type===a)return this;for(var b=0;b<this.b.length;b++){if(this.b[b].type===a)return this.b[b];var c=this.b[b].get(a);if(c)return c}return null};W.prototype.a=function(){var a=Math.pow(2,32)-1;var b=4+this.type.length;"uuid"===this.type&&(b+=16);if(0<this.b.length)for(var c=0;c<this.b.length;c++)b+=this.b[c].a();this.size>a&&(b+=8);return b};
W.prototype.write=function(a){var b=Math.pow(2,32)-1;this.start=a.getPosition();this.size=this.a();this.size>b?_.P(a,1):_.P(a,this.size);_.Sh(a,Ko(this.type));this.size>b&&Eo(a,this.size);"uuid"===this.type&&_.Sh(a,null);if(0<this.b.length&&!this.j)for(b=0;b<this.b.length;b++)this.b[b].write(a),this.b[b].a(),a.getPosition()};_.w(X,W);X.prototype.a=function(){return 4+W.prototype.a.call(this)};X.prototype.write=function(a){W.prototype.write.call(this,a);Fo(a,this.version);Go(a,this.flags)};
_.w(Oo,W);Oo.prototype.a=function(){return this.c.byteLength+W.prototype.a.call(this)-this.offset};Oo.prototype.write=function(a){W.prototype.write.call(this,a);_.Sh(a,this.c,this.offset);a.getPosition()};_.w(Po,X);Po.prototype.a=function(){return this.c.byteLength+X.prototype.a.call(this)-this.offset};Po.prototype.write=function(a){X.prototype.write.call(this,a);_.Sh(a,this.c,this.offset);a.getPosition()};_.w(Qo,W);
Qo.prototype.a=function(){var a=this.f.length;a=a+4+this.c.join("").length;return a+W.prototype.a.call(this)};Qo.prototype.write=function(a){W.prototype.write.call(this,a);_.Sh(a,Ko(this.f));_.P(a,this.df);_.Sh(a,Ko(this.c.join("")));a.getPosition()};_.w(Ro,W);_.w(So,W);_.w(To,X);To.prototype.a=function(){var a=0;a=1===this.version?a+28:a+16;a=a+44+this.c.length;return a+=X.prototype.a.call(this)};
To.prototype.write=function(a){X.prototype.write.call(this,a);1===this.version?(Eo(a,0),Eo(a,0),_.P(a,this.timescale),Eo(a,this.duration*this.timescale)):(_.P(a,0),_.P(a,0),_.P(a,this.timescale),_.P(a,this.duration*this.timescale));_.P(a,65536);Ho(a,this.volume);Ho(a,0);_.P(a,0);_.P(a,0);for(var b=0;b<this.c.length;b++)Fo(a,this.c[b]);_.P(a,0);_.P(a,0);_.P(a,0);_.P(a,0);_.P(a,0);_.P(a,0);_.P(a,this.f);a.getPosition()};_.w(Uo,W);_.w(Vo,X);Vo.prototype.a=function(){return 20+X.prototype.a.call(this)};
Vo.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.c);_.P(a,1);_.P(a,0);_.P(a,0);_.P(a,0);a.getPosition()};_.w(Wo,X);Wo.prototype.a=function(){var a=0;a=1===this.version?a+32:a+20;a=a+24+this.c.length;return a+X.prototype.a.call(this)};
Wo.prototype.write=function(a){X.prototype.write.call(this,a);1===this.version?(Eo(a,0),Eo(a,0),_.P(a,this.f),_.P(a,0),Eo(a,this.duration*this.timescale)):(_.P(a,0),_.P(a,0),_.P(a,this.f),_.P(a,0),_.P(a,this.duration*this.timescale));_.P(a,0);_.P(a,0);Ho(a,0);Ho(a,0);Ho(a,this.volume);Ho(a,0);for(var b=0;b<this.c.length;b++)Fo(a,this.c[b]);Ho(a,this.width);Ho(a,0);Ho(a,this.height);Ho(a,0);a.getPosition()};_.w(Xo,X);Xo.prototype.a=function(){var a=0;a=1===this.version?a+28:a+16;return a+4+X.prototype.a.call(this)};
Xo.prototype.write=function(a){X.prototype.write.call(this,a);1===this.version?(Eo(a,0),Eo(a,0),_.P(a,this.timescale),Eo(a,this.duration*this.timescale)):(_.P(a,0),_.P(a,0),_.P(a,this.timescale),_.P(a,this.duration*this.timescale));Ho(a,this.language);Ho(a,0);a.getPosition()};_.w(Yo,X);Yo.prototype.a=function(){return 33+X.prototype.a.call(this)};
Yo.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,0);this.c===_.Xd?_.Sh(a,Ko("vide")):_.Sh(a,Ko("soun"));_.P(a,0);_.P(a,0);_.P(a,0);this.c===_.Xd?_.Sh(a,Ko("VideoHandler\x00")):_.Sh(a,Ko("SoundHandler\x00"));a.getPosition()};_.w(Zo,X);Zo.prototype.a=function(){return 2+this.c.byteLength+X.prototype.a.call(this)};Zo.prototype.write=function(a){X.prototype.write.call(this,a);Ho(a,0);_.Sh(a,this.c);a.getPosition()};_.w($o,W);$o.prototype.a=function(){return 8+W.prototype.a.call(this)};
$o.prototype.write=function(a){W.prototype.write.call(this,a);_.P(a,0);Ho(a,0);Ho(a,1)};_.w(ap,$o);ap.prototype.a=function(){return 70+$o.prototype.a.call(this)};ap.prototype.write=function(a){$o.prototype.write.call(this,a);Ho(a,0);Ho(a,0);_.P(a,0);_.P(a,0);_.P(a,0);Ho(a,this.width);Ho(a,this.height);_.P(a,4718592);_.P(a,4718592);_.P(a,0);Ho(a,1);Fo(a,10);_.Sh(a,Ko("AVC Coding",31));Ho(a,24);Jo(a,-1)};_.w(bp,$o);bp.prototype.a=function(){return 20+$o.prototype.a.call(this)};
bp.prototype.write=function(a){$o.prototype.write.call(this,a);_.P(a,0);_.P(a,0);Ho(a,this.channelCount);Ho(a,this.sampleSize);Jo(a,0);Ho(a,0);Ho(a,this.sampleRate);Ho(a,0)};_.w(cp,ap);cp.prototype.write=function(a){ap.prototype.write.call(this,a);for(var b=0;b<this.b.length;b++)this.b[b].write(a);a.getPosition()};_.w(dp,cp);_.w(ep,bp);ep.prototype.write=function(a){bp.prototype.write.call(this,a);for(var b=0;b<this.b.length;b++)this.b[b].write(a);a.getPosition()};_.w(fp,ep);_.w(gp,W);
gp.prototype.a=function(){for(var a=7,b=0;b<this.ka.length;b++)a+=2,a+=this.ka[b].byteLength;for(b=0;b<this.ka.length;b++)a+=2,a+=this.Ya[b].byteLength;return a+W.prototype.a.call(this)};
gp.prototype.write=function(a){W.prototype.write.call(this,a);Fo(a,this.version);Fo(a,this.f);Fo(a,this.g);Fo(a,this.c);Fo(a,255);Fo(a,224|this.ka.length);for(var b=0;b<this.ka.length;b++)Ho(a,this.ka[b].length),_.Sh(a,this.ka[b]);Fo(a,this.Ya.length);for(b=0;b<this.Ya.length;b++)Ho(a,this.Ya[b].length),_.Sh(a,this.Ya[b]);a.getPosition()};_.w(hp,X);hp.prototype.a=function(){return 22+(this.Ra.byteLength+3)+X.prototype.a.call(this)};
hp.prototype.write=function(a){X.prototype.write.call(this,a);Fo(a,3);Fo(a,23+this.Ra.byteLength);Ho(a,1);Fo(a,0);Fo(a,4);Fo(a,15+this.Ra.byteLength);Fo(a,64);Fo(a,21);Go(a,0);_.P(a,0);_.P(a,0);Fo(a,5);Fo(a,this.Ra.byteLength);_.Sh(a,this.Ra);_.Sh(a,new Uint8Array([6,1,2]));a.getPosition()};_.w(ip,X);ip.prototype.a=function(){return this.location.length+X.prototype.a.call(this)};ip.prototype.write=function(a){X.prototype.write.call(this,a);0<this.location.length&&_.Sh(a,Ko(this.location));a.getPosition()};
_.w(jp,X);jp.prototype.a=function(){for(var a=4,b=0;b<this.entries.length;b++)a+=this.entries[b].a();return a+X.prototype.a.call(this)};jp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.entries.length);for(var b=0;b<this.entries.length;b++)this.entries[b].write(a);a.getPosition()};_.w(kp,W);_.w(lp,X);lp.prototype.a=function(){for(var a=4,b=0;b<this.entries.length;b++)a+=this.entries[b].a();return a+X.prototype.a.call(this)};
lp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.entries.length);for(var b=0;b<this.entries.length;b++)this.entries[b].write(a);a.getPosition()};_.w(mp,X);mp.prototype.a=function(){for(var a=4,b=0;b<this.entries.length;b++)a+=this.entries[b].a();return a+X.prototype.a.call(this)};mp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.entries.length);for(var b=0;b<this.entries.length;b++)this.entries[b].write(a);a.getPosition()};_.w(np,X);
np.prototype.a=function(){for(var a=4,b=0;b<this.entries.length;b++)a+=this.entries[b].a();return a+X.prototype.a.call(this)};np.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.entries.length);for(var b=0;b<this.entries.length;b++)this.entries[b].write(a);a.getPosition()};_.w(op,X);op.prototype.a=function(){for(var a=4,b=0;b<this.entries.length;b++)a+=this.entries[b].a();return a+X.prototype.a.call(this)};
op.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.entries.length);for(var b=0;b<this.entries.length;b++)this.entries[b].write(a);a.getPosition()};_.w(pp,X);pp.prototype.a=function(){return 8+X.prototype.a.call(this)};pp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,0);_.P(a,0);a.getPosition()};_.w(qp,X);qp.prototype.a=function(){return 4+X.prototype.a.call(this)};qp.prototype.write=function(a){X.prototype.write.call(this,a);Jo(a,0);Ho(a,0);a.getPosition()};
_.w(rp,W);_.w(sp,W);_.w(tp,W);_.w(up,X);up.prototype.a=function(){var a=0;a=1===this.version?a+8:a+4;return a+X.prototype.a.call(this)};up.prototype.write=function(a){X.prototype.write.call(this,a);1===this.version?Eo(a,this.c):_.P(a,this.c);a.getPosition()};_.w(vp,X);vp.prototype.a=function(){return 4+X.prototype.a.call(this)};vp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.c);a.getPosition()};_.w(wp,X);
wp.prototype.a=function(){var a=4;this.flags&sq&&(a+=4);this.flags&tq&&(a+=4);for(var b=0;b<this.c;b++)this.flags&uq&&(a+=4),this.flags&vq&&(a+=4),this.flags&wq&&(a+=4),this.flags&xq&&(a+=4);return a+X.prototype.a.call(this)};
wp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.c);this.flags&sq&&(a.getPosition(),Io(a,this.g));this.flags&tq&&_.P(a,this.h);for(var b=0;b<this.c;b++)this.flags&uq&&_.P(a,this.i[b]),this.flags&vq&&_.P(a,this.sampleSize[b]),this.flags&wq&&_.P(a,this.l[b]),this.flags&xq&&(0===this.version?_.P(a,this.f[b]):Io(a,this.f[b]));a.getPosition()};var sq=1,tq=4,uq=256,vq=512,wq=1024,xq=2048;_.w(xp,X);
xp.prototype.a=function(){var a=4;this.flags&yq&&(a+=8);this.flags&zq&&(a+=4);this.flags&Aq&&(a+=4);this.flags&Bq&&(a+=4);this.flags&Cq&&(a+=4);return a+X.prototype.a.call(this)};xp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.c);this.flags&yq&&Eo(a,this.f);this.flags&zq&&_.P(a,this.l);this.flags&Aq&&_.P(a,this.g);this.flags&Bq&&_.P(a,this.i);this.flags&Cq&&_.P(a,this.h);a.getPosition()};var yq=1,zq=2,Aq=8,Bq=16,Cq=32;_.w(yp,W);_.w(zp,W);_.w(Ap,W);
Ap.prototype.a=function(){return this.c.byteLength+W.prototype.a.call(this)};Ap.prototype.write=function(a){W.prototype.write.call(this,a);0<this.c.byteLength&&_.Sh(a,this.c)};_.w(Bp,X);Bp.prototype.a=function(){var a=20;1===this.c&&0===this.f&&(a=a+1+this.g.length);return a+X.prototype.a.call(this)};
Bp.prototype.write=function(a){X.prototype.write.call(this,a);Fo(a,0);0===this.version?Fo(a,0):Fo(a,0);Fo(a,this.c);Fo(a,this.f);_.Sh(a,_.ei(this.h));if(1===this.c&&0===this.f){Fo(a,0);for(var b=0;b<this.g.length;b++)Fo(a,this.g[b])}a.getPosition()};_.w(Cp,X);Cp.prototype.a=function(){var a=8;this.flags&1&&(a+=Ko(this.Za).byteLength);return a+X.prototype.a.call(this)};Cp.prototype.write=function(a){X.prototype.write.call(this,a);_.Sh(a,Ko(this.c));_.P(a,this.f);this.flags&1&&_.Sh(a,Ko(this.Za));a.getPosition()};
_.w(Dp,W);Dp.prototype.a=function(){return Ko(this.c).byteLength+W.prototype.a.call(this)};Dp.prototype.write=function(a){W.prototype.write.call(this,a);_.Sh(a,Ko(this.c));a.getPosition()};_.w(Ep,X);Ep.prototype.a=function(){var a=0;this.flags&1&&(a+=8);a+=4;for(var b=0;1>b;b++)a=0===this.version?a+4:a+8;return a+X.prototype.a.call(this)};
Ep.prototype.write=function(a){X.prototype.write.call(this,a);this.flags&1&&(_.P(a,0),_.P(a,0));_.P(a,1);for(var b=0;1>b;b++)0===this.version?_.P(a,this.offset[b]):Eo(a,this.offset[b]);a.getPosition()};_.w(Fp,X);Fp.prototype.a=function(){var a=0;this.flags&1&&(a+=8);a+=5;0===this.c&&(a+=this.g.length);return a+X.prototype.a.call(this)};
Fp.prototype.write=function(a){X.prototype.write.call(this,a);this.flags&1&&(_.P(a,0),_.P(a,0));Fo(a,this.c);_.P(a,this.f);if(0===this.c)for(var b=0;b<this.f;b++)Fo(a,this.g[b]);a.getPosition()};_.w(Gp,X);Gp.prototype.a=function(){var a=4;this.flags&1&&(a+=1);for(var b=0;b<this.f;b++)if(a+=this.c[b].Ze.byteLength,this.flags&2){a+=2;for(var c=0;c<this.c[b].dc;c++)a+=2,a+=4}return a+X.prototype.a.call(this)};
Gp.prototype.write=function(a){X.prototype.write.call(this,a);_.P(a,this.f);this.flags&1&&Fo(a,this.g);for(var b=0;b<this.f;b++)if(_.Sh(a,this.c[b].Ze),this.flags&2){Ho(a,this.c[b].dc);for(var c=0;c<this.c[b].dc;c++)Ho(a,this.c[b].ae[c].me),_.P(a,this.c[b].ae[c].ne)}a.getPosition()};var Ip=/^(\d{2,}):(\d{2}):(\d{2}):(\d{2})\.?(\d+)?$/,Jp=/^(?:(\d{2,}):)?(\d{2}):(\d{2})$/,Kp=/^(?:(\d{2,}):)?(\d{2}):(\d{2}\.\d{2,})$/,Lp=/^(\d*\.?\d*)f$/,Mp=/^(\d*\.?\d*)t$/,Np=/^(?:(\d*\.?\d*)h)?(?:(\d*\.?\d*)m)?(?:(\d*\.?\d*)s)?(?:(\d*\.?\d*)ms)?$/;var Up=[162,57,79,82,90,155,79,20,162,68,108,66,124,100,141,244];_.r=bq.prototype;_.r.configure=function(a){this.j=a};_.r.start=function(a,b){var c=this;this.a=b;this.i=Xp(a);return cq(this).then(function(d){return kq(c,d.data).then(function(){qq(c,c.o);return c.g})})};_.r.stop=function(){this.a&&this.a.networkingEngine.$d(this.A);this.o=this.f=this.g=this.j=this.a=null;this.h&&(clearTimeout(this.h),this.h=null);this.v=!1;return Promise.resolve()};_.r.update=function(){var a=this;if(this.mc())return cq(this).then(function(b){return kq(a,b.data).then(function(){return a.g})})["catch"](function(b){if(a.a)a.a.onError(b)})};
_.r.onExpirationUpdated=function(){};_.r.Wg=function(){var a=this;this.b.debug(_.Ya);this.a&&(this.h=null,this.update().then(function(){qq(a,a.o)})["catch"](function(b){a.a&&(_.jf(b,1),a.a.onError(b),qq(a,0))}))};_.r.mc=function(){return this.F===fq};_.r.Kd=function(){return 0<this.l.length};_.r.We=function(a){var b=null;if(this.l.length)for(var c=0;c<this.l.length;c++)if(this.l[c].keySystem===a){b=this.l[c].initData[0];break}return b};
_.r.Ni=function(a){var b=this.f.timescale,c={isLive:this.mc.bind(this),vc:this.Kd.bind(this),Eh:function(){return 1},Bd:this.We.bind(this)};if(a.request.type!==_.Bn||a.uri.startsWith("data:"))return Promise.resolve(a);var d=!1,e=new _.K(_.M,3,4035,null),f=null;try{f=Wp(a,b,c)}catch(g){d=!0,e.data=g,3E3===g.code&&(e.code=4039)}if(d||!f)return Promise.reject(e);a.data=f;return Promise.resolve(a)};var oq={video:_.Zd,audio:_.Jb,text:_.Cb},aq="VOD",fq="LIVE",pq={Zi:"caption",dj:_.Cd};_.w(rq,_.wl);rq.prototype.ub=function(){_.Sn.ed("ism",bq);_.Sn.Ac(_.Dk,bq)};rq.prototype.cb=function(){_.Sn.Zd("ism");_.Sn.fd(_.Dk)};rq.prototype.id=function(){return"clpp.component.smooth"};_.B("clpp.smooth.SmoothComponent",rq);};f.call(g, window);