import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var ao="No thumbnail duration or URL specified",bo="No thumbnail found for position ",co="Position is out of range: ",eo="Stream configuration is invalid",fo="Thumbnail URL is mandatory",go="Wrong gridSize format",ho="clpp.thumbnails",io=function(a,b,c,d,e,f,g,h,l,m,n,p){d=void 0===d?0:d;e=void 0===e?0:e;f=void 0===f?0:f;g=void 0===g?0:g;h=void 0===h?1:h;l=void 0===l?1:l;m=void 0===m?0:m;n=void 0===n?0:n;p=void 0===p?new Image:p;this.time=b;this.a=p;this.src=a;this.duration=c;this.x=d;this.y=e;this.width=
f;this.height=g;this.c=h;this.h=l;this.f=m;this.g=n;this.b=null},jo=function(){this.b=new _.E(ho);this.a=this.c=null},ko=function(a){if(!a)return null;a=new _.Dh(a);return a.path.match(/.*\.vtt$/i)?"WEBVTT":a.path.match(/.*\.bif$/i)?"BIF":a.path.match(/.*\.(png|jpg|jpeg)$/i)?"SINGLE":null},lo=function(){},mo=function(){this.log=new _.E(ho);this.h=null;this.b=[];this.u=!1},oo=function(a,b){b.reduce(function(c,d){var e=d,f=!1;typeof d===_.Xc&&(e=d.step,f=d.preloadWhileBuffering);return c.then(function(){return no(a,
0,e,!!f)})},Promise.resolve())},no=function(a,b,c,d){if(a.u||b>=a.b.length)return Promise.resolve();var e=b+c;return po(a,d).then(function(){return a.b[b].load()}).then(function(){return no(a,e,c,d)})},po=function(a,b){return new Promise(function(c){if(b||a.h.getState()!==_.Cm)c();else a.h.one(_.Tb,function(){c()})})},qo=function(){mo.call(this);this.a=null;this.g=this.c=1;this.f=0},ro=function(a){mo.call(this);this.o=a;this.a=null;this.g=this.c=1;this.j=this.l=0;this.f=1;this.i=-1},so=function(a,
b){if(!b||_.J.H(b.horizontalTiles)||_.J.H(b.verticalTiles)||_.J.H(b.width)||_.J.H(b.height)||0>=b.horizontalTiles||0>=b.verticalTiles||0>=b.width||0>=b.height)throw new _.K(_.M,7,7100,"Selected stream contains one or more invalid configuration values");a.a=b;a.c=a.a.horizontalTiles||1;a.g=a.a.verticalTiles||1;a.f=a.c*a.g;a.i=a.a.durationPerTile||0;var c=a.a.width,d=a.a.height;void 0!==c&&(a.l=c/a.c);void 0!==d&&(a.j=d/a.g)},to=function(){mo.call(this);this.a=null},uo=function(a){a=a.split(/\.|:/).map(parseFloat);
var b=0,c,d={3:.001,2:1,1:60,0:3600};for(c=a.length-1;0<=c;c--)b+=a[c]*d[c];return b},vo=function(a,b){this.time=a;this.duration=0;this.offset=b;this.length=0;this.a=new _.Of},wo=function(){this.c=new _.E(ho);this.b=new ArrayBuffer(0);this.a=[];this.f=new _.Of},xo=function(a){var b=a.b.byteLength;a.a.forEach(function(c){c.offset+c.length<b&&c.a.resolve()})},zo=function(a,b){return yo(a,b).then(function(c){return new io(c,b.time,b.duration)})},yo=function(a,b){return b.load().then(function(){var c=
_.N(a.b);c=new Uint8Array(Array.prototype.slice.call(c,b.offset,b.offset+b.length));return"data:image/jpeg;base64,"+_.tf(c)})};io.prototype.raw=function(){return this.a.cloneNode(!1)};
io.prototype.element=function(a,b){var c=this.width,d=this.height,e=this.width/this.height;void 0!==a&&void 0===b&&(b=0);null!==a&&void 0!==a&&(c=a);null!==b&&void 0!==b&&(d=b);c||(c=Math.ceil(d*e));d||(d=Math.ceil(c/e));e=document.createElement("div");e.style.width=c+"px";e.style.height=d+"px";e.style.backgroundColor="#000";e.style.backgroundRepeat="no-repeat";e.style.backgroundImage="url("+this.src+")";e.style.backgroundSize=Math.ceil(c/this.width*(this.a.naturalWidth||this.a.width))+"px "+Math.ceil(d/
this.height*(this.a.naturalHeight||this.a.height))+"px";var f=this.y/this.height;e.style.backgroundPositionX="-"+this.x/this.width*c+"px";e.style.backgroundPositionY="-"+f*d+"px";return e};
io.prototype.load=function(){var a=this;this.b||(this.b=new Promise(function(b,c){function d(){a.width||(a.width=(a.a.naturalWidth||a.a.width)/a.c);a.height||(a.height=(a.a.naturalHeight||a.a.height)/a.h);a.x||(a.x=a.width*a.f);a.y||(a.y=a.height*a.g)}if(a.a.src&&a.a.complete)d(),b(a);else{var e=null,f=function(){d();a.a.removeEventListener("load",f);a.a.removeEventListener(_.zc,e);b(a)};e=function(){a.a.removeEventListener("load",f);a.a.removeEventListener(_.zc,e);c()};a.a.addEventListener("load",
f);a.a.addEventListener(_.zc,e);a.a.src=a.src}}));return this.b};_.B("clpp.thumbnails.Thumbnail",io);io.prototype.load=io.prototype.load;io.prototype.element=io.prototype.element;io.prototype.raw=io.prototype.raw;_.r=jo.prototype;_.r.onPlayerCreated=function(a){this.c=a};_.r.onPlayerWillDestroy=function(){this.c=null};_.r.onPlayerWillRelease=function(){this.a=null};
_.r.onContentWillLoad=function(a){var b=this,c=a.getConfiguration();if(c.thumbnails){var d=c.thumbnails;d&&(void 0===d.enabled||d.enabled)&&((c=d.mode)||(c=ko(d.url||null)),c&&("SINGLE"===c||"GRID"===c?this.a=new qo:"WEBVTT"===c?this.a=new to:"BIF"===c&&(this.a=new wo)),this.a&&(this.b.info("Loading thumbs configuraiton",d),this.c.one(_.Pc,function(){b.b.info("Initialize thumbnails provider");b.a.init(a,d)})))}else this.a=null};
_.r.onContentLoaded=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.a||(d=(d=a.getConfiguration())&&d.thumbnails,d&&void 0!==d.enabled&&!d.enabled)||(c=c&&c.find(function(e){return Array.isArray(e)&&0<e.length}),this.b.info(_.Yc,c),c&&(this.a=new ro(c),this.a.init(a,d)))};_.r.get=function(a){return this.a?this.a.get(a):Promise.reject()};_.r.id=function(){return"thumbnails"};_.B("clpp.thumbnails.ThumbnailsPlugin",jo);jo.prototype.get=jo.prototype.get;jo.Id="thumbnails";
lo.prototype.create=function(){return new jo};_.hl(new lo);mo.prototype.init=function(a,b){var c=this;this.h=a;a.one(_.pd,function(){c.u=!0});a.isLive()||this.m().then(function(){b&&b.preload&&oo(c,b.preload)})};_.w(qo,mo);
qo.prototype.init=function(a,b){if(!b||!b.url)throw new _.K(_.M,7,7100,fo);if("GRID"===b.mode&&!b.gridSize)throw new _.K(_.M,7,7100,"Grid size is mandatory for GRID mode");if(!b.duration)throw new _.K(_.M,7,7100,"Duration is mandatory");this.a=b;var c=this.a.duration,d=this.a.url;if(!c||!d)throw this.log.error(ao,c,d),new _.K(_.M,7,7100,ao);this.f=c;if(this.a.gridSize)try{var e=this.a.gridSize.split(/x/).map(function(f){return parseInt(f,10)}).filter(function(f){return 0<f});if(2===e.length)this.c=e[0],
this.g=e[1];else throw new _.K(_.M,7,7100,go);}catch(f){throw this.log.error("Error during parsing gridSize",f),new _.K(_.M,7,7100,go);}mo.prototype.init.call(this,a,b)};qo.prototype.get=function(a){var b=this.h.getDuration();if(void 0===this.a.duration)return Promise.reject("Duration configuration not defined");var c=Math.floor(a/this.a.duration);if(0>a||a>b)return Promise.reject(co+a);var d=this.b[c];return d?d.load().then(function(){return d}):Promise.reject(bo+a+" at index "+c)};
qo.prototype.m=function(){if(0<this.b.length)return Promise.resolve();var a=this.h.getDuration(),b=this.c*this.g;a=Math.ceil(Math.ceil(a/this.f)/b);for(var c=this.a.templateKey||"$index$",d=0;d<a;d++)for(var e=this.a.url.replace(c,String(d+1)),f=new Image,g=0;g<b;g++)this.b.push(new io(e,this.f*(d*b+g),this.f,0,0,0,0,this.c,this.g,g%this.c,Math.floor(g/this.c),f));return Promise.resolve()};_.w(ro,mo);ro.prototype.init=function(a,b){this.log.debug("init start");if(0===this.o.length)throw new _.K(_.M,7,7100,"Player does not return any thumbnails");this.o.sort(function(c,d){return void 0!==c.bandwidth&&void 0!==d.bandwidth?c.bandwidth-d.bandwidth:0});try{so(this,this.o[0])}catch(c){throw c;}mo.prototype.init.call(this,a,b)};
ro.prototype.get=function(a){if(0>a)return this.log.error("Position must be greater than 0 but is "+a),Promise.reject();if(!this.a)return this.log.error(eo),Promise.reject();var b=this.a.findSegmentPosition(a);if(null===b||void 0===b)return this.log.error("Could not find segment index for specified position",a),Promise.reject();var c=this.a.getSegmentReference(b);if(c){var d=this.i?this.i*this.f:c.endTime-c.startTime,e=d/this.f;a=Math.floor((a-c.startTime)/d*this.f);var f;if(0<this.b.length)e=this.a.findSegmentPosition(0),
null!==e&&(f=this.b[(b-e)*this.f+a]);else if((d=c.c())&&0<d.length){var g=0,h=0;c=c.startTime;1<this.f&&(g=a%this.c,h=Math.floor(a/this.c),c+=a*e);f=new io(d[0],c,e,this.l*g,this.j*h,this.l,this.j,this.c,this.g,g,h)}if(f)return f.load().then(function(){return f})}this.log.error("segment reference for specified segment index does not exist",b);return Promise.reject()};
ro.prototype.m=function(){if(0<this.b.length)return Promise.resolve();if(!this.a)return this.log.error(eo),Promise.reject();for(var a=this.a.findSegmentPosition(0),b;null!==a&&!_.J.H(b=this.a.getSegmentReference(a++));)for(var c=b.c()[0],d=new Image,e=b.startTime,f=this.i?this.i*this.f:b.endTime-b.startTime,g=f/this.f,h=0;h<this.g;++h)for(var l=0;l<this.c;++l)this.b.push(new io(c,e+h*f+l*g,g,this.l*l,this.j*h,this.l,this.j,this.c,this.g,l,h,d));return Promise.resolve()};_.w(to,mo);
to.prototype.init=function(a,b){var c=this;if(!b||!b.url)throw new _.K(_.M,7,7100,fo);var d=b.url,e=_.hg(d);e.type=_.gg;this.a=a.getNetworkEngine().fetch(e).promise.then(function(f){if(f=f.data){f=_.mf(f).split(/\n/);for(var g=0;g<f.length;g++){var h=f[g],l=h.split(" --\x3e ");if(2===l.length){h=f[++g];var m=h.indexOf("\x3d");var n=0>m?[]:h.substr(m+1).split(/,/).map(parseFloat);m=n[0];var p=n[1],q=n[2];n=n[3];var t=h.indexOf("#");h=0>t?h:h.substr(0,t);h.match(/^http|^\/\//)||(h=d.substr(0,d.lastIndexOf("/"))+
"/"+h);t=uo(l[0]);l=uo(l[1])-t;c.b.push(new io(h,t,l,m,p,q,n,0,0))}}}})["catch"](function(f){c.log.error("[VTT] Error while loading thumbnail",f)});mo.prototype.init.call(this,a,b)};to.prototype.get=function(a){var b=this;return 0>a?Promise.reject(co+a):this.a.then(function(){for(var c={},d=0;d<b.b.length;c={fb:c.fb},d++)if(c.fb=b.b[d],c.fb.time>=a&&a<c.fb.time+c.fb.duration)return c.fb.load().then(function(e){return function(){return e.fb}}(c));return Promise.reject(bo+a)})};to.prototype.m=function(){return this.a};vo.prototype.load=function(){return this.a};
wo.prototype.init=function(a,b){var c=this;if(!b||!b.url)throw new _.K(_.M,7,7100,fo);var d=_.hg(b.url);d.type=_.gg;a.getNetworkEngine().fetch(d).promise.then(function(e){e=e.data;var f=_.N(c.b);e=_.N(e);for(var g=f.byteLength+e.byteLength,h=new ArrayBuffer(g),l=new DataView(h),m=0,n=0,p=f.byteLength;n<p;n++)l.setUint8(m,f[n]),m+=1;f=0;for(n=e.byteLength;f<n;f++)l.setUint8(m,e[f]),m+=1;c.b=h;c.c.info("Appended "+e.byteLength+" bytes. Total data now "+g+" bytes.")}).then(function(){var e=c.b,f=_.N(e),
g=String.fromCharCode.apply(null,Ao),h=Array.prototype.slice.call(f,0,8);f=64;var l=0;var m=!1;if(g===String.fromCharCode.apply(null,h))for(e=new DataView(e,16,20),e=e.getUint32(0,!0),0===e&&(e=1E3);!m;){l+=1;h=e;g=new DataView(c.b,f);m=g.getUint32(0,!0);h=m*h/1E3;g=g.getUint32(4,!0);g=new vo(h,g);if(h=c.a.length)h=c.a[h-1],h.length=g.offset-h.offset,h.duration=g.time-h.time;c.a.push(g);f+=8;(m=4294967295===m)&&c.f.resolve();if(1E5<l)throw Error("There was a problem during reading BIF entries");}else throw Error("The file is not a valid BIF format");
}).then(function(){xo(c)})["catch"](function(e){c.c.error("Error while loading thumbnail index",e)})};wo.prototype.get=function(a){var b=this;return 0>a?Promise.reject(co+a):this.f.then(function(){for(var c=0;c<b.a.length;c++){var d=b.a[c];if(d.time>=a&&a<d.time+d.duration)return zo(b,d).then(function(e){return e.load().then(function(){return e})})}return Promise.reject(bo+a)})};var Ao=[137,66,73,70,13,10,26,10];};f.call(g, window);