import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var aw="An unknown error occured while trying to get volume",bw="Cannot get loading rendition due to platform limitations",cw="SecurityError",dw="The require privilege is: http://tizen.org/privilege/tv.audio",ew="onbufferingcomplete",fw="onbufferingprogress",gw="onbufferingstart",hw="oncurrentplaytime",iw="ondrmevent",jw="onerror",kw="onstreamcompleted",lw="onsubtitlechange",mw="preparingend",nw="preparingstart",ow="|STARTBITRATE\x3d",pw=function(a,b,c){function d(e){c.call(a,e);a.removeEventListener(b,
d)}a.addEventListener(b,d)},qw=function(a,b){var c={},d=null!==a.parentElement?window.getComputedStyle(a,null):a.style;if(!b||0===b.length){b||(b=[]);for(var e in d)b.push(e)}b.forEach(function(f){c[f]=d[f]});return c},rw=function(a){this.g=a;this.h=new _.E("clpp.tizen.TextDisplayer");this.b=[];this.c=this.a=null;this.j=this.f=this.i=!1},sw=function(a){a.f||(a.a=new _.sg(function(){a.h.debug("onTick_()");if(!a.i&&a.j){var b=a.g.getPosition();a.c&&a.c.endTime<b&&a.g.trigger(new _.I(_.oc));for(var c=
null,d=0;d<a.b.length;d++){var e=a.b[d];if(e.startTime<=b&&b<=e.endTime){c=e;break}}(b=c)&&b!==a.c&&(a.c=b,a.g.trigger(new _.I(_.pc,{cue:{text:b.payload||"",startTime:b.startTime,endTime:b.endTime,align:b.textAlign,id:b.id,line:_.Pb,lineAlign:b.lineAlign,Fi:!1,position:_.Pb,positionAlign:b.positionAlign||_.Pb,size:b.size||100,snapToLines:!0,vertical:""}})))}}),a.a.za(.1))},tw=function(){this.f=this.a=this.c=null;this.g={};this.b=new _.E("clpp.tizen.TrackManager");this.l=this.i=this.h=null;this.j=
1},uw=function(a,b){a.c.trigger(new _.I(_.ae,{details:{width:b.width,height:b.height,bandwidth:b.bandwidth,track:b.track,abrSelection:a.a.g}}))},vw=function(a){var b=a.V();b&&a.c.trigger(new _.I(_.Rb,{detail:{width:b.width,height:b.height,bandwidth:b.bandwidth,rendition:b}}))},zw=function(a,b){if(b){var c=b.track.type.toUpperCase(),d=a.a,e=Number(b.id);c.toUpperCase()===ww&&xw(d,!0);try{webapis.avplay.setSelectTrack(c.toUpperCase(),e)}catch(f){d.a.error(f)}c===yw&&(a.h=b,a.c.trigger(new _.I(_.Ob)));
c===ww&&(a.i=b,a.c.trigger(new _.I(_.Id)))}else a.b.debug("Must provide valid rendition")},Aw=function(a,b,c){c.language=b.language||null;c.channelsCount=b.channels?Number(b.channels):null;c.mimeType=_.Jb;a=new _.oj(String(a),c);a.track=c;a.codec=b.fourCC||null;a.bandwidth=b.bit_rate||null;return a},Bw=function(a,b,c){c.mimeType=_.Zd;a=new _.oj(String(a),c);a.track=c;a.width=b.Width||null;a.height=b.Height||null;a.bandwidth=b.Bit_rate?Number(b.Bit_rate):null;a.codec=b.fourCC||null;return a},Cw=function(a,
b,c){c.mimeType="text/ttml";c.language=b.track_lang||null;c.kind=_.Dd;return new _.oj(String(a),c)},Dw=function(a,b){var c=null;try{c=JSON.parse(b)}catch(d){a.b.warn("Couldn't retrieve extra infos from stream."),c=null}return c},Hw=function(a,b){function c(n,p){for(var q=0;q<n.length;q++)if(n[q].language===p)return n[q];return null}var d={};if(0>=b.length)return d;for(var e=b.filter(function(n){return n.type===Ew}),f=b.filter(function(n){return n.type===yw}),g=[],h=0;h<f.length;h++){var l=Dw(a,f[h].extra_info);
if(l){var m=c(g,l.language);m||(m=new _.nj(String(a.j++),_.S),g.push(m));m.renditions.push(Aw(f[h].index,l,m))}else a.b.warn("Skipping audio stream with no extra info")}f=new _.nj(String(a.j++),_.qj);for(h=0;h<e.length;h++)(l=Dw(a,e[h].extra_info))?f.renditions.push(Bw(e[h].index,l,f)):a.b.warn("Skipping video stream with no extra info");e=[];e=a.f?Fw(a.f):Gw(a,b);d[_.qj]=[f];d[_.S]=g;d[_.R]=e;return d},Gw=function(a,b){for(var c=b.filter(function(h){return h.type===ww}),d=[],e=0;e<c.length;e++){var f=
Dw(a,c[e].extra_info);if(f){var g=new _.nj(String(a.j++),_.R);g.renditions.push(Cw(c[e].index,f,g));d.push(g)}else a.b.warn("Skipping text stream with no extra info")}return d},Iw=function(a,b){for(var c=a.g[_.qj]||[],d=[],e=0;e<c.length;e++)for(var f=0;f<c[e].renditions.length;f++)_.J.ua(c[e].renditions[f],b,Object.keys(b))&&d.push(c[e].renditions[f]);return d[0]||null},Lw=function(a,b){if(b===_.R&&a.f)return Jw(a.f);var c=(Kw(a.a)||[]).filter(function(e){return e.type===b.toUpperCase()})[0],d=null;
b===_.qj&&(d=Dw(a,c.extra_info),d=Iw(a,{width:d.Width,height:d.Height}));b===_.S&&(c?a.h=d:d=a.h);b===_.R&&(c?a.i=d:d=a.i);return d},Mw=function(a){_.bf.call(this);this.f=a;this.a=new _.E("clpp.tizen.Middleware");this.j=1;this.l=["LOCALE","DISPLAY"];this.i=!1;this.h=null;this.m=0;this.g=!0;this.c=!1;this.b=null},Nw=function(a){var b=a.l;if(0===b.length)return!0;b.forEach(function(c){tizen.systeminfo.getPropertyValue(c,function(){a.l.splice(a.l.indexOf(c),1)},function(d){a.a.debug(c+": err: ",d)})});
return 0===a.l.length},Ow=function(a){try{webapis.avplay.setListener({onbufferingstart:a.Zg.bind(a),onbufferingprogress:a.Yg.bind(a),onbufferingcomplete:a.Xg.bind(a),onstreamcompleted:a.bh.bind(a),oncurrentplaytime:function(b){a.trigger(new _.I(hw,{currentTime:b}))},onevent:a.ah.bind(a),onsubtitlechange:a.dh.bind(a),ondrmevent:a.$g.bind(a),onerror:a.Rb.bind(a)})}catch(b){a.a.error(b)}},Pw=function(a,b){a.a.debug("Applying drm",b.drm);var c=_.ph[b.drm.env]||null;if(c){var d=b.drm.customData||{};if((c=
_.oh(c)[_.nh])&&c.licenseUrl){var e={DeleteLicenseAfterUse:!0};e.CustomData=btoa(JSON.stringify(d));e.licenseServer=c.licenseUrl;try{webapis.avplay.setDrm("PLAYREADY","SetProperties",JSON.stringify(e))}catch(f){d=f,a.a.error(d),a.Rb(JSON.stringify(d))}}}else a.a.debug("Could not find configured DRM environment.","Please make sure "+b.drm.env+" is registered.")},Qw=function(a){var b=!!a.f.getTrackManager().fa();try{webapis.avplay.setSilentSubtitle(!b)}catch(c){a.a.debug("Could not set AVPlay subtitle config",
c)}a.a.debug("AVPlay is prepared")},Rw=function(a,b){try{var c=b.estimatedBandwidth||0,d=b.currentBandwidth||0;a.a.debug({estimatedBandwidth:c,hj:d});0!==c&&0!==d&&c>=1.15*d&&webapis.avplay.setStreamingProperty("ADAPTIVE_INFO",ow+d)}catch(e){a.a.debug(e)}},Sw=function(a,b){try{webapis.avplay.setStreamingProperty("ADAPTIVE_INFO","|BITRATES\x3d"+b+ow+b)}catch(c){throw a.a.debug("Could not set fixed bandwdth",c),c;}},Vw=function(a){return{position:a.getPosition(),state:a.f.getState(),ke:a.getState(),
playbackRate:a.getPlaybackRate(),isLive:a.isLive(),duration:a.getDuration(),isMuted:Tw(a),volume:a.getVolume(),Ti:Uw(a),nh:Kw(a)}},Xw=function(a){var b,c,d,e;return _.z(function(f){if(1==f.a)return _.x(f,Ww(),2);if(3!=f.a)return b=new Promise(function(g){(new _.sg(g)).P(5)}),d=new Promise(function(g){c=new _.sg(function(){Nw(a)&&g()});c.za(.01)}),_.x(f,Promise.race([d.then(function(){return!0}),b.then(function(){return!1})]),3);e=f.b;c&&(c.stop(),c=null);if(!e)return a.a.debug("Took to long for the SDK to be ready"),
f["return"](Promise.reject("SDK Timeout"));_.y(f)})},Zw=function(a,b,c){a.h=_.Gk(b);var d=a.m,e=c||{estimatedBandwidth:0,currentBandwidth:0,nextBandwidth:null,currentPosition:0};return new Promise(function(f,g){a.a.debug("Loading manifest URL: "+a.h[d].url);var h=b.startTime||void 0;a.c&&(a.trigger(new _.I(gw)),h=c.currentPosition);try{webapis.avplay.open(a.h[d].url),e.nextBandwidth?(Sw(a,e.nextBandwidth),a.g=!1):(a.g||Rw(a,e),a.g=!0)}catch(l){return g(l)}Ow(a);b.drm&&b.drm.env?Pw(a,b):a.a.debug("No DRM configuration was provided. Assuming clear content");
try{a.c||a.trigger(new _.I(nw)),a.a.debug("avplay.prepare()"),webapis.avplay.prepareAsync(function(){a.a.debug("AVPlay is ready!");a.c||a.trigger(new _.I(mw));h&&typeof h===_.Wc&&0<h&&a.seek(h)["catch"](function(l){a.a.debug("Couldn't set start position",l)});Qw(a);a.c||(b.volume&&a.setVolume(b.volume),b.muted&&Yw(a,b.muted),b.autoplay&&a.play()["catch"](function(l){a.a.debug("Autoplay failed",l)}));return f(a)},function(l){a.a.debug("prepareAsync failed",l);a.trigger(new _.I(jw));return g(l)})}catch(l){return a.a.debug("prepareAsync didnt even run correctly",
l),g(l)}})},ax=function(a,b,c){a.a.debug("switchVideoTrack()");try{var d={estimatedBandwidth:parseInt(webapis.avplay.getStreamingProperty("CURRENT_BANDWITH"),10),currentBandwidth:b,nextBandwidth:c,currentPosition:a.getPosition()};a.b=Vw(a);a.c=!0;webapis.avplay.stop();webapis.avplay.close();return a.load(a.f.getConfiguration(),d).then(function(){var e=a.b.ke;a.c=!1;a.b=null;return e===$w?a.pause():a.play()})}catch(e){return Promise.reject(e)}},Uw=function(a){return a.c&&a.b?a.b.Ti:webapis.avplay.getTotalTrackInfo()},
Kw=function(a){return a.c&&a.b?a.b.nh:webapis.avplay.getCurrentStreamInfo()},xw=function(a,b){if(!b){var c=_.Xj();a.f.trigger(new _.I(_.oc,c))}c=a.f.f;try{c?bx(c,b):webapis.avplay.setSilentSubtitle(!b)}catch(d){a.a.debug("Could not set text track visibility",d)}},Yw=function(a,b){try{tizen.tvaudiocontrol.setMute(b)}catch(c){switch(c.name){case cw:a.a.warn("The application does not have the privilege to set mute.",dw);break;default:a.a.warn(aw,c)}}},Tw=function(a){var b=null;try{b=tizen.tvaudiocontrol.isMute()}catch(c){switch(c.name){case cw:a.a.warn("The application doesn't have the privilege to get the mute state.",
dw);break;default:a.a.warn(aw,c)}}return!!b},Ww=function(){return new Promise(function(a,b){if(window.hasOwnProperty("webapis"))a();else{var c=document.createElement("script");pw(c,"load",function(d){return a(d)});pw(c,_.zc,function(d){return b(d)});c.src="$WEBAPIS/webapis/webapis.js";document.querySelector("head").appendChild(c)}})},cx=function(){this.j=this.m=this.c=this.f=this.o=this.a=this.i=this.h=null;this.l=!0;this.g=null;this.b=new _.E("clpp.tizen.TextStreamer")},dx=function(a){var b,c;return _.z(function(d){if(1==
d.a)return b=a.a.getConfiguration(),_.x(d,_.Sn.create(a.o.url,a.a.getNetworkEngine(),b.manifest.attemptParameters,a.o.type),2);c=d.b;c.configure(b.manifest);return d["return"](c)})},ex=function(a){var b=document.createElement(_.Xd),c=new _.Sr;a=new rw(a.a);var d=new _.zr(function(){return null});return new _.Zr(b,c,a,d)},fx=function(a){var b={Ka:function(){return a.a.getPosition()},K:a.f,Ab:a.a.getNetworkEngine(),Rd:a.fh.bind(a),Qd:a.eh.bind(a),onError:a.gh.bind(a),onEvent:function(){},jf:a.hh.bind(a),
Zc:function(){},zd:function(){return new _.Is}};return new _.Mt(a.h,b)},gx=function(a){var b=a.a.getPosition(),c=null;a=_.v(a.h.periods);for(var d=a.next();!d.done;d=a.next())d=d.value,d.startTime<=b&&(c=d);return c},Fw=function(a){a.b.info("getTextStreams()",a.h);if(a.h){var b=[],c=a.h.periods;a.b.info("getting text streams");for(var d=0;d<c.length;d++)if(a.b.info(c[d].startTime,a.a.getPosition()),c[d].startTime<=a.a.getPosition()){b=c[d].textStreams;break}a=b}else a=[];b=[];for(d=c=0;d<a.length;d++){var e=
new _.nj(String(c++),_.R);e.mimeType=a[d].mimeType;e.language=a[d].language;e.roles=a[d].roles;e.kind=a[d].kind||_.Dd;var f=new _.oj(String(a[d].id),e);f.bandwidth=a[d].bandwidth||null;e.renditions.push(f);b.push(e)}return b},Jw=function(a){if(a.f&&!a.f.h.isTextVisible())return null;if(a.c){var b=_.Ot(a.c,_.k),c=null;if(b){a=Fw(a);for(var d=0;d<a.length;d++)if(a[d].renditions[0].id===String(b.id)){c=a[d].renditions[0];break}}return c}return null},hx=function(a,b){a.b.debug("Set active track",b);if(b&&
(a.j=b.language,a.m=b.roles[0]||"",a.h&&a.c)){bx(a,!0);var c=gx(a),d=b.renditions[0];(c=c.textStreams.find(function(e){return String(e.id)==d.id}))?(a.l?(a.b.debug("Switching period defer text selection"),a.g=c):(_.Wt(a.c,c,!0,0),a.a.trigger(new _.I(_.Id))),a.j=c.language):a.b.error(_.Yq,d.id)}},bx=function(a,b){a.b.debug("Set text visibility",b);a.f&&a.f.h.setTextVisibility(b)},jx=function(){_.bf.call(this);this.a=new Mw(this);this.c=new ix(this);this.g=this.l=_.Kg();this.j=null;this.b=new _.E("clpp.tizen.Player");
this.i=null;this.h=new tw;this.m=new _.fg;this.f=null},kx=function(a){if("NONE"!==a.a.getState()){var b=qw(a.j.c,[_.he,_.Dc]);a.b.debug("Got dimensions",b);var c=Math.min(1920,parseInt(b.width,10)||0);b=Math.min(1080,parseInt(b.height,10)||0);a.b.debug("Applying dimensions: ",c,b);a=c;c=b;var d=b=0;b=void 0===b?0:b;d=void 0===d?0:d;a=void 0===a?1920:a;c=void 0===c?1080:c;var e=webapis.avplay;e.setDisplayRect(b,d,a,c);0===b&&0===d&&1920===a&&1080===c&&e.setDisplayMethod("PLAYER_DISPLAY_MODE_LETTER_BOX")}else a.b.debug("Could not apply dimension. Player state "+
a.a.getState())},mx=function(){this.name=lx},nx=function(){this.a=null},ix=function(a){this.f=a;this.a=this.f.a;this.b=_.ym;this.g=_.zm;this.j=(new Date).getTime();this.i=-1;this.h=2;this.c=new _.E("clpp.tizen.StateManager")},px=function(a,b){if(a.b!==b)if(a.b===_.qk&&b!==_.ym)a.c.debug(_.ar+ox(b));else{var c=(new Date).getTime();a.g=a.b;a.b=b;a.b===_.Cm?(a.i=(new Date).getTime(),a.f.trigger(new _.I(_.Ub,{detail:{bufferedTimeMS:-1,reason:a.h}}))):a.g===_.Cm&&a.f.trigger(new _.I(_.Tb,{detail:{bufferedTimeMS:c-
a.i,reason:a.h}}));var d={currentState:a.b,previousState:a.g,timeSinceLastStateChangeMS:c-a.j};a.j=c;a.f.trigger(new _.I(_.zd,{detail:d}));a.c.debug("State changed:",ox(a.g),"-\x3e",ox(a.b))}},ox=function(a){return Object.keys(_.Gm)[a]},rx=function(a){var b=a.a.getState(),c=a.b;switch(b){case qx:c=_.el;break;case $w:c=_.Jm;break;default:a.f.isEnded()?c=_.Em:a.c.debug("Inconsistent AVPlay plackback state:",b)}px(a,c)};_.r=rw.prototype;_.r.append=function(a){if(!this.f){this.h.debug("append cues");this.i=!0;a.sort(function(c,d){return c.startTime-d.startTime});var b=this.b.findIndex(function(c){return c.startTime>=a[0].startTime});0===b&&(this.b=[]);0<b&&(this.b=this.b.slice(0,b));Array.prototype.push.apply(this.b,a);this.i=!1;this.a||sw(this)}};_.r.remove=function(a,b){if(this.f)return!1;this.h.debug("Remove cues",a,b);return!0};_.r.isTextVisible=function(){return this.j};
_.r.setTextVisibility=function(a){(this.j=a)&&!this.a&&sw(this);a||(this.a&&(this.a.stop(),this.a=null),this.g.trigger(new _.I(_.oc)))};_.r.destroy=function(){var a=this;return _.z(function(b){a.f=!0;a.a&&(a.a.stop(),a.a=null);a.b=[];_.y(b)})};_.w(tw,_.U);_.r=tw.prototype;_.r.ef=function(a){var b=a.eventid;a=a.data;switch(b){case sx:0<Object.keys(this.g).length||(this.b.debug("Loading track manager!"),this.load());b=+Dw(this,webapis.avplay.getCurrentStreamInfo()[0].extra_info).Bit_rate;if(b=Iw(this,{bandwidth:b}))this.l=b,uw(this,b);break;case tx:vw(this);break;default:this.b.debug("Event type: "+b+" data: "+a)}};_.r.Td=function(a){a.detail.currentState===_.el&&this.c.off(_.zd,this.Td)};
_.r.Sa=function(a){this.c=a;this.a=this.c.a;this.a.on("onevent",this.ef,this)};_.r.release=function(){this.g={};this.f=this.l=this.i=this.h=null;this.j=1};_.r.load=function(){if(this.a&&!(0<Object.keys(this.g).length)){this.f=this.c.f;this.c.off(_.zd,this.Td);this.c.on(_.zd,this.Td,this);var a=Uw(this.a);this.g=Hw(this,a);if(a=this.g[_.S])this.h=a[0].renditions[0]||null;vw(this)}};_.r.destroy=function(){this.a.off("onevent",this.ef);this.a=this.c=null};
_.r.getVideoTracks=function(){return this.g[_.qj]||[]};_.r.getAudioTracks=function(){return this.g[_.S]||[]};_.r.U=function(){return this.g[_.R]||[]};_.r.V=function(){return Lw(this,_.qj)};_.r.ma=function(){return Lw(this,_.S)};_.r.fa=function(){return Lw(this,_.R)};_.r.Ca=function(){return this.l};_.r.Aa=function(){this.b.info(bw);return null};_.r.Ba=function(){this.b.info(bw);return null};_.r.ga=function(){var a=this.V();return a?a.track:null};
_.r.ba=function(){var a=this.ma();return a?a.track:null};_.r.ca=function(){var a=this.fa();return a?a.track:null};_.r.ya=function(a){var b=this;null===a?(a=this.V(),ax(this.a,a.bandwidth,null).then(function(){vw(b)})):0<a.renditions.length&&this.xa(a.renditions[0])};_.r.ia=function(a){a?zw(this,a.renditions[0]):this.b.warn("Cannot disable audio tracks on this platform.","Consider muting audio instead...")};
_.r.ja=function(a){a?(a=a.renditions[0],this.f?hx(this.f,a.track):zw(this,a)):(this.b.debug("Disabling text tracks"),this.i=null,xw(this.a,!1),this.c.trigger(new _.I(_.Id)))};
_.r.xa=function(a){var b=this,c=this.V();this.a.g||a.width!==c.width||a.height!==c.height||a.bandwidth!==c.bandwidth?(this.l=a,uw(this,a),ax(this.a,c.bandwidth,a.bandwidth).then(function(){vw(b)})["catch"](function(d){var e=new _.K(_.M,7,7200,{tizenerror:d});b.b.debug("Error while switching video track",d);b.c.onError(e)})):this.b.debug("Trying to switch to already active rendition. Doing nothing...")};_.r.Ea=function(a){zw(this,a)};_.r.Fa=function(a){this.f?hx(this.f,a.track):zw(this,a)};
_.r.addTextTrack=function(){};_.r.na=function(){return this.a.g};tw.prototype.isAbrEnabled=tw.prototype.na;tw.prototype.addTextTrack=tw.prototype.addTextTrack;tw.prototype.setTextRendition=tw.prototype.Fa;tw.prototype.setAudioRendition=tw.prototype.Ea;tw.prototype.setVideoRendition=tw.prototype.xa;tw.prototype.setTextTrack=tw.prototype.ja;tw.prototype.setAudioTrack=tw.prototype.ia;tw.prototype.setVideoTrack=tw.prototype.ya;tw.prototype.getTextTrack=tw.prototype.ca;tw.prototype.getAudioTrack=tw.prototype.ba;
tw.prototype.getVideoTrack=tw.prototype.ga;tw.prototype.getLoadingTextRendition=tw.prototype.Ba;tw.prototype.getLoadingAudioRendition=tw.prototype.Aa;tw.prototype.getLoadingVideoRendition=tw.prototype.Ca;tw.prototype.getTextRendition=tw.prototype.fa;tw.prototype.getAudioRendition=tw.prototype.ma;tw.prototype.getVideoRendition=tw.prototype.V;tw.prototype.getTextTracks=tw.prototype.U;tw.prototype.getAudioTracks=tw.prototype.getAudioTracks;tw.prototype.getVideoTracks=tw.prototype.getVideoTracks;_.w(Mw,_.bf);_.r=Mw.prototype;_.r.Zg=function(){this.c||this.trigger(new _.I(gw))};_.r.Yg=function(a){this.trigger(new _.I(fw,{percent:a}))};_.r.Xg=function(){this.trigger(new _.I(ew))};_.r.bh=function(){this.trigger(new _.I(kw))};_.r.ah=function(a,b){this.trigger(new _.I("onevent",{eventid:a,data:b}))};_.r.dh=function(a,b,c,d,e){this.trigger(new _.I(lw,{duration:a,text:b,subtitleType:c,attriCount:d,attributes:e}))};_.r.$g=function(a,b){this.trigger(new _.I(iw,{drmType:a,drmData:b}))};
_.r.Rb=function(a){this.trigger(new _.I(jw,{eventType:a}))};
_.r.play=function(){function a(){return new Promise(function(d,e){function f(){d();clearTimeout(g)}var g=null;b.one(hw,f,b);g=setTimeout(function(){b.off(hw,f);e("Timeout")},3E4)})}var b=this,c=this.getState();if(c===ux)return(new Promise(function(d,e){webapis.avplay.prepareAsync(function(){Qw(b);d(webapis.avplay.play())},function(f){b.trigger(new _.I(jw));e(f)})})).then(function(){return a()});if(c===$w||c===vx)try{return webapis.avplay.play(),a()}catch(d){return Promise.reject(d)}return c===qx?
Promise.resolve():Promise.reject("Player is in invalid state")};_.r.pause=function(){try{webapis.avplay.pause()}catch(a){Promise.reject(a)}return this.getState()===$w?Promise.resolve():Promise.reject()};
_.r.setPlaybackRate=function(a){var b=this.getState();if(b===vx||b===qx||b===$w){try{webapis.avplay.setSpeed(a),this.j=a}catch(c){return this.a.debug("Error while trying to set playback rate",c),this.setPlaybackRate(this.j)}return!0}this.a.debug("Cannot set playback rate; AVPlay is in inconsistent state: "+b);return!1};_.r.getPlaybackRate=function(){return this.j};
_.r.load=function(a,b){var c=this;return _.z(function(d){return 1==d.a?(c.a.debug("configure()",b||""),_.x(d,Xw(c),2)):_.x(d,Zw(c,a,b),0)})};_.r.getState=function(){if(this.c&&this.b)return this.b.ke;try{return webapis.avplay.getState()}catch(a){this.Rb(JSON.stringify(a))}};_.r.seek=function(a){var b=this,c=1E3*a;return new Promise(function(d,e){b.i=!0;b.f.trigger(new _.I(_.Td));webapis.avplay.seekTo(c,function(){b.i=!1;b.f.trigger(new _.I(_.Sd));d()},function(){b.i=!1;e()})})};
_.r.getPosition=function(){if(this.c&&this.b)return this.b.position;try{return webapis.avplay.getCurrentTime()/1E3}catch(a){this.Rb(JSON.stringify(a))}};_.r.getDuration=function(){if(this.c&&this.b)return this.b.duration;try{return webapis.avplay.getDuration()/1E3}catch(a){this.Rb(JSON.stringify(a))}};_.r.release=function(){var a=this;return new Promise(function(b,c){try{return webapis.avplay.stop(),webapis.avplay.close(),a.j=1,a.i=!1,a.h=null,a.b=null,b()}catch(d){return c(d)}})};
_.r.getVolume=function(){var a=null;try{a=tizen.tvaudiocontrol.getVolume()}catch(b){switch(b.name){case cw:this.a.debug("The application does not have the privilege to get the volume.",dw);break;default:this.a.debug(aw,b)}}return a};
_.r.setVolume=function(a){try{tizen.tvaudiocontrol.setVolume(Math.max(0,Math.min(100*a,100)))}catch(b){switch(b.name){case "InvalidValueError":this.a.warn("Invalid value passed for setVolume.","The passed value value should be in the range of 0 to 1.");break;case cw:this.a.warn("The application does not have the privilege to set the volume.",dw);break;default:this.a.warn("An unknown error occured while trying to set volume",b)}}};
_.r.isLive=function(){if(this.c&&this.b)return this.b.isLive;try{return"1"===webapis.avplay.getStreamingProperty("IS_LIVE")}catch(a){this.Rb(JSON.stringify(a))}};_.r.stop=function(){try{webapis.avplay.stop()}catch(a){this.a.debug(a)}};_.r.setSourceIndex=function(a){this.m=a};_.r.getSourceIndex=function(){return this.m};_.r.getLoadedSource=function(){return this.h&&this.h[this.getSourceIndex()]};
var ux="IDLE",vx="READY",qx="PLAYING",$w="PAUSED",Ew="VIDEO",yw="AUDIO",ww="TEXT",tx="PLAYER_MSG_RESOLUTION_CHANGED",sx="PLAYER_MSG_BITRATE_CHANGE";_.r=cx.prototype;
_.r.load=function(a){var b=this,c,d,e,f,g,h;return _.z(function(l){switch(l.a){case 1:if(!b.a)return l["return"]();b.o=a;c=b;return _.x(l,dx(b),2);case 2:return c.i=l.b,d={networkingEngine:b.a.getNetworkEngine(),filterNewPeriod:function(){},filterAllPeriods:function(){},onTimelineCueAdded:function(){},onEvent:function(){},onError:function(){}},l.c=3,e=b,_.x(l,b.i.start(a.url,d),5);case 5:e.h=l.b;_.Be(l,4);break;case 3:return f=_.Ce(l),b.b.error(f),g=b,_.x(l,b.i.start(a.url.replace("https://","http://"),
d),6);case 6:g.h=l.b;case 4:return b.f=ex(b),_.x(l,b.f.v,7);case 7:b.c=fx(b),h=b.a.getConfiguration(),b.c.h=h.streaming,b.j=h.preferredTextLanguage,b.m=h.preferredTextRole,_.y(l)}})};_.r.fh=function(a){this.b.debug(_.hr,a);this.l=!0;var b=_.vs(a.textStreams,this.j||"",this.m||"")[0]||null;this.g&&(a.textStreams.includes(this.g)&&(b=this.g),this.g=null);return{variant:null,text:b}};_.r.eh=function(){this.b.debug("canSwitch_");this.l=!1;this.g&&(_.Wt(this.c,this.g,!0,0),this.g=null)};_.r.gh=function(){this.b.debug("onError_")};
_.r.hh=function(){this.i&&this.i.update&&this.i.update()};_.r.start=function(){var a=this;return _.z(function(b){try{a.c.start()}catch(c){a.b.error("Error while starting streaming engine",c)}_.y(b)})};_.r.release=function(){var a=this;return _.z(function(b){a.a=null;a.h=null;a.o=null;a.m=null;a.j=null;a.l=!0;a.g=null;_.y(b)})};
_.r.destroy=function(){var a=this;return _.z(function(b){switch(b.a){case 1:if(!a.i){b.a=2;break}return _.x(b,a.i.stop(),3);case 3:a.i=null;case 2:if(!a.c){b.a=4;break}return _.x(b,a.c.destroy(),5);case 5:a.c=null,a.l=!0;case 4:if(!a.f){b.a=0;break}return _.x(b,a.f.destroy(),7);case 7:a.f=null,_.y(b)}})};_.w(jx,_.bf);_.r=jx.prototype;_.r.Be=function(){var a=this;this.b.debug("On Stream completed. Current time: ",this.getPosition());this.trigger(new _.I(_.yc));this.g.loop?this.seek(this.g.startTime||0)["catch"](function(){a.b.debug("Could not loop playback")}):this.a.stop()};_.r.ye=function(a){this.trigger(new _.I(_.Md,{currentTime:a.currentTime/1E3}))};
_.r.Ce=function(a){var b=/&lt;.?br&gt;/g,c=_.Xj(),d=this.a.getPosition(),e=d+a.duration/1E3;a=a.text||"";this.b.debug("Got subtitles: ",a);c.startTime=d;c.endTime=e;a?(c.text=a.replace(b,""),b=new _.I(_.pc,{cue:c})):b=new _.I(_.oc,{cue:c});this.trigger(b)};_.r.ze=function(a){this.b.debug("DRM event: "+a.drmType+", data: "+a.drmData)};
_.r.Ae=function(a){this.b.debug("Error: TYPE: "+a.eventType);px(this.c,_.qk);a=new _.K(_.M,7,7200,{tizenerror:a.eventType});this.a.release();this.trigger(new _.I(_.zc,{detail:a}))};
_.r.init=function(a,b){this.g=this.l=b;this.j=a;this.a.on(kw,this.Be,this);this.a.on(hw,this.ye,this);this.a.on(lw,this.Ce,this);this.a.on(iw,this.ze,this);this.a.on(jw,this.Ae,this);var c=this.c;c.a.on(gw,c.Fe,c);c.a.on(fw,c.Ee,c);c.a.on(ew,c.De,c);c.a.on(nw,c.mf,c);c.a.on(mw,c.lf,c);c.a.on(kw,c.Ge,c);c.a.on(hw,c.He,c);this.h.Sa(this);this.b.debug("Initializing player surface");c=this.j;var d=c.D(),e=c.b.css;d?_.Sg(d,e.hidden):c.g.debug("No media element available that could be hidden");this.i=_.Qg(_.Xc,
{id:"TizenPlayer",type:"application/avplayer"});this.j.Lc(this.i,!0);if(d=this.j.D())c=this.i,d=qw(d,[_.he,_.Dc,"position"]),_.Ug(c,d),kx(this)};_.r.getSurface=function(){return this.j};_.r.getConfiguration=function(){return this.g};
_.r.destroy=function(){var a=this;return _.z(function(b){switch(b.a){case 1:return _.x(b,a.release(),2);case 2:a.a.off(kw,a.Be);a.a.off(hw,a.ye);a.a.off(lw,a.Ce);a.a.off(iw,a.ze);a.a.off(jw,a.Ae);if(!a.f){b.a=3;break}return _.x(b,a.f.destroy(),4);case 4:a.f=null;case 3:a.i&&(a.i.parentElement.removeChild(a.i),a.i=null),a.h.destroy(),a.c.destroy(),a.h=null,a.c=null,_.y(b)}})};_.r.namespace=function(){return lx};_.r.getPlaybackRate=function(){return this.a.getPlaybackRate()};_.r.setPlaybackRate=function(a){this.a.setPlaybackRate(a)};
_.r.getPosition=function(){return this.c.getState()===_.Em?this.getDuration():this.a.getPosition()||0};_.r.seek=function(a){return typeof a===_.Wc&&0<=a?(this.isLive()||(a=Math.min(a,this.getDuration())),this.a.seek(a)):Promise.reject()};_.r.getPresentationStartTime=function(){return 0};_.r.getSeekRange=function(){return{start:0,end:0}};_.r.getVolume=function(){var a=this.a.getVolume();return typeof a===_.Wc?a/100:null};_.r.setVolume=function(a){this.a.setVolume(a)};_.r.getDuration=function(){return this.a.getDuration()};
_.r.getBufferInfo=function(){this.b.warn(_.ka);return new _.Le};_.r.getTrackManager=function(){return this.h};_.r.unload=function(){var a=this;return this.a.release().then(function(){a.h.release()})};_.r.release=function(){var a=this;return _.z(function(b){if(1==b.a)return a.f?b=_.x(b,a.f.release(),2):(b.a=2,b=void 0),b;if(4!=b.a)return _.x(b,a.a.release(),4);a.h.release();a.c.release();_.y(b)})};
_.r.load=function(a){var b=this,c,d,e;return _.z(function(f){switch(f.a){case 1:_.Og(a)&&(b.g=_.Ng(b.l,a));c=_.Gk(b.g)[0];d=!!b.g.tizen&&b.g.tizen.sideStreamText;if(!d){f.a=2;break}b.f=new cx;b.f.a=b;f.c=3;return _.x(f,b.f.load(c),5);case 5:_.Be(f,4);break;case 3:e=_.Ce(f),b.b.error(e);case 4:b.f.start();case 2:return _.x(f,b.a.load(b.g),6);case 6:b.h.load(),_.y(f)}})};_.r.play=function(){var a=this;this.trigger(new _.I(_.kd));kx(this);return this.a.play().then(function(){rx(a.c)})};
_.r.pause=function(){var a=this;return this.a.pause().then(function(){rx(a.c)})};_.r.getState=function(){return this.c.getState()};_.r.getThumbnailStreams=function(){return[]};_.r.onError=function(a){var b=new _.I(_.zc,{detail:a});a.a===_.M&&px(this.c,_.qk);this.trigger(b)};_.r.getDrmInfo=function(){return null};_.r.isEnded=function(){return this.c.getState()===_.Em};_.r.isPaused=function(){return this.a.getState()===$w};_.r.isMuted=function(){return Tw(this.a)};
_.r.setMuted=function(a){Yw(this.a,a)};_.r.getNetworkEngine=function(){return this.m};_.r.setNetworkEngine=function(a){this.m=a};_.r.isLive=function(){return this.a.isLive()};_.r.getStats=function(){return null};_.r.setSourceIndex=function(a){this.a.setSourceIndex(a)};_.r.getSourceIndex=function(){return this.a.getSourceIndex()};_.r.getLoadedSource=function(){return this.a.getLoadedSource()};_.r.canPlay=function(a){return(new mx).canPlay(a)};_.r.getTimelineCues=function(){return[]};
jx.prototype.setNetworkEngine=jx.prototype.setNetworkEngine;jx.prototype.getNetworkEngine=jx.prototype.getNetworkEngine;var lx="clpp.tizen";mx.prototype.canPlay=function(a){a=a.type;a=a===_.Bk||a===_.Ck||a===_.Dk;var b=window.hasOwnProperty("webapis");return _.ng()&&a&&b};mx.prototype.create=function(){return new jx};mx.prototype.create=mx.prototype.create;mx.prototype.canPlay=mx.prototype.canPlay;_.w(nx,_.wl);nx.prototype.ub=function(){this.a=new mx;_.gf(this.a)};nx.prototype.cb=function(){if(this.a){var a=this.a.name;a&&_.ef[a]&&(delete _.ef[a],_.ff.info("Removed Player factory: '"+a+"'"));this.a=null}};nx.prototype.id=function(){return"clpp.component.tizen"};_.B("clpp.tizen.TizenComponent",nx);_.r=ix.prototype;_.r.release=function(){px(this,_.ym)};_.r.destroy=function(){this.release();this.a.off(gw,this.Fe);this.a.off(fw,this.Ee);this.a.off(ew,this.De);this.a.off(nw,this.mf);this.a.off(mw,this.lf);this.a.off(kw,this.Ge);this.a.off(hw,this.He);this.f=this.a=null};_.r.Fe=function(){this.c.debug("Buffering start. Player state: ",this.a.getState());this.h=this.a.i?1:2;px(this,_.Cm)};_.r.Ee=function(a){this.c.debug("Buffering progress: "+a.percent+" %. Player state: ",ox(this.b))};
_.r.De=function(){this.c.debug("Buffering complete. Player state: ",this.a.getState());var a;if(a=this.b!==_.Mn)a=this.a.getState(),a=a===qx||a===$w;a&&rx(this)};_.r.mf=function(){this.c.debug("Preparing starts. AVPlay State: ",this.a.getState());this.a.getState()===ux?px(this,_.Mn):this.c.error("AVPlay prepares while state is not IDLE")};_.r.lf=function(){this.c.debug("Preparing ends: AVPlay state:",this.a.getState())};
_.r.He=function(){this.b===_.el||this.b!==_.Jm&&this.b!==_.Em&&this.b!==_.Cm||px(this,_.el)};_.r.Ge=function(){px(this,_.Em)};_.r.getState=function(){return this.b};};f.call(g, window);