import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var Oo="Registering listeners",Po="clpp.vimond.VimondPlugin",Qo=function(){this.a=!1;this.f=new _.H(Po);this.g=this.c=this.b=null},Ro=function(){},So=function(a,b,c,d,e){this.i=a;this.h=c;this.c=b;this.a=d;this.g=e;this.f=new _.H("clpp.vimond.VimondService");this.b=0},To=function(a){this.a=a;this.b=new _.ii;this.f=new _.H("clpp.vimond.VimondAdapter");this.c=this.g=!1;this.a&&this.b&&(this.f.debug(Oo),this.b.on(this.a,_.qd,this.Xi.bind(this)),this.b.on(this.a,_.db,this.yh.bind(this)),this.b.on(this.a,
_.eb,this.zh.bind(this)))},Uo=function(a,b){var c=a.a.getState();if(1===b)return["str-start",_.kd];if(a.g)return[_.yc,_.gd];if(c===_.En)return[_.yc,null];if(c===_.dl)return[_.Ac,_.gd];var d=_.gd;if(c===_.Cn||c===_.ln||a.c)d=_.kd;return["period",d]},Vo=function(a,b,c,d,e){this.w=a;this.A=b;this.B=c;this.b=d;this.u=e;this.c=new _.ii;this.i=!0;this.f=this.h=this.m=!1;this.o=null;this.g=new _.Hf(this.Ze.bind(this));this.a=new _.H("clpp.vimond.VimondDispatcher");this.j=this.l=0;this.b&&this.c&&(this.a.debug(Oo),
this.c.on(this.b,_.Dd,this.Ch.bind(this)),this.c.on(this.b,_.Nd,this.Dh.bind(this)),this.c.on(this.b,_.db,this.Ah.bind(this)),this.c.on(this.b,_.eb,this.Bh.bind(this)))},Wo=function(a,b){a.b.trigger(new _.O(_.be,{detail:b}))},Xo=function(a,b,c){b&&(a.m=!0,a.g.stop());a.b.onError(new _.J(b?_.K:1,9,9201,c))};_.w(Qo,_.fo);_.r=Qo.prototype;_.r.onPlayerCreated=function(){};
_.r.onContentWillLoad=function(a){var b=a.getConfiguration();(this.a=!_.C.I(b.vimond)&&typeof b.vimond===_.$c)?a.namespace()===_.dc&&(this.a=!1,this.f.info("Vimond does not report when casting.")):this.f.warn("Vimond plugin is loaded but not configured. Will do nothing.");if(this.a){b=a.getConfiguration().vimond;for(var c=_.u(["authToken","playerEventRequest"]),d=c.next();!d.done;d=c.next())if(d=d.value,!b[d]){this.f.warn(d+" key is missing");a.onError(new _.J(1,9,9200));return}this.f.debug("Configuration is valid");
c=b.failIfUnreachable;typeof c!==_.Ub&&(c=!0);d=b.failOnError;typeof d!==_.Ub&&(d=!0);this.b=new To(a);this.c=new So(b.playerEventRequest.uri,b.authToken,b.playerEventRequest.body,this.b,a.getNetworkEngine());this.g=new Vo(b.playerEventRequest.eventInterval,c,d,a,this.c)}};_.r.onPlayerWillRelease=function(){this.a&&(this.b&&this.b.dispose(),this.g&&this.g.dispose(),this.g=this.c=this.b=null)};_.r.onPlayerWillDestroy=function(){};_.r.id=function(){return"vimond"};
_.r.ue=function(a){this.a&&this.c&&this.c.ue(a)};_.B(Po,Qo);Qo.prototype.updateAuthToken=Qo.prototype.ue;Qo.Id="vimond";Ro.prototype.create=function(){return new Qo};_.xn(new Ro);So.prototype.ue=function(a){this.c=a};_.r=To.prototype;_.r.getPosition=function(){return Math.floor(this.a.getPosition())};_.r.Xi=function(){this.g=!0};_.r.yh=function(){this.c=!0};_.r.zh=function(){this.c=!1};_.r.dispose=function(){this.f.debug(_.Za);_.li(this.b)};_.r=Vo.prototype;_.r.Dh=function(){this.f||(this.f=1<Math.abs(this.l-this.b.getPosition()));this.l=this.b.getPosition()};_.r.Ah=function(){this.a.debug("Ad break started");this.h=!0};_.r.Bh=function(){this.a.debug("Ad break stopped");this.h=!1};
_.r.Ch=function(a){var b=this,c,d,e,f,g;return _.A(function(h){if(1==h.a){c=a.detail;d=_.Gn;e=c.currentState;f=c.previousState;b.a.debug("State changed, prev: "+f+" curr: "+e);if(b.m||b.h)return h["return"]();if(e===b.o&&!b.f)return b.a.debug("Ignore transition"),h["return"]();if(b.i&&e!==d.PLAYING)return h["return"]();if(b.f&&[d.PAUSED,d.BUFFERING].includes(e))return b.a.debug("Seeking"),h["return"]();b.f&&e===d.PLAYING&&(b.a.debug("Seeked"),b.f=!1);g=[d.PLAYING,d.PAUSED,d.ERROR,d.ENDED];if(!g.includes(e))return h.C(0);
b.o=e;return _.x(h,b.Ze(),3)}e===d.ENDED&&b.g.stop();_.y(h)})};
_.r.Ze=function(){var a=this,b,c,d,e,f,g;return _.A(function(h){if(1==h.a){b=_.no;var l=Math.floor(Date.now()/1E3);0<a.j&&a.a.debug("Last event was "+(l-a.j)+" seconds ago");a.j=l;a.g.stop();a.g.R(a.i?10:a.w);a.i=!1;_.Ce(h,2);l=a.u;l.b++;var m=_.C.eb(l.h);m.client.buildName=_.ka;m.client.buildVersion=_.da;var n=m.client,p=l.a.a.getDrmInfo();n.drm=p?p.keySystem:"";m.client.pageUrl=document.location.href;m.client.streamUrl=l.a.a.getLoadedSource().url;m.client.userAgent=navigator.userAgent;m.client.videoFormat=
l.a.a.getLoadedSource().type||"";n=m.client;p=l.a.a.getLoadedSource();p=((new _.Rj(p.url)).scheme||"").replace(":","");n.videoProtocol=p;n=Uo(l.a,l.b);m.client.playerEvent=n[0];m.client.playerState=n[1];m.progress.vod&&(m.progress.vod.position=l.a.getPosition());if(n=m.progress.live){p=l.a;p=Math.floor(p.a.getPresentationStartTime()+p.a.getPosition());p=(new Date(1E3*p)).toISOString();n.position=p;var q=l.a;p=q.a.getPosition();q=q.a.getSeekRange().end;n.onLiveEdge=30>Math.abs(q-p);typeof n.liveResumePossible!==
_.Ub&&(n.liveResumePossible=!0)}m.progress.eventNumber=l.b;m.timestamp=(new Date).toISOString();l.f.debug("Fire an event");n=_.Gi(l.i);n.method="POST";n.contentType="application/json";n.headers.Authorization="Bearer "+l.c;n.body=_.sf(JSON.stringify(m));l=l.g.fetch(n).promise;return _.x(h,l,4)}if(2!=h.a)return c=h.b,Wo(a,c),_.De(h,0);e=d=_.Ee(h);f=e.code;g=e.data;[b.Kj,b.TIMEOUT].includes(f)?(a.a.debug("Unreachable service"),Wo(a,g),Xo(a,a.A,g)):f===b.Hj?(a.a.debug("Generic service error"),Wo(a,g),
Xo(a,a.B,g)):a.a.error(d.toString());_.y(h)})};_.r.dispose=function(){this.a.debug(_.Za);_.li(this.c);this.g.stop()};};f.call(g, window);