import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var Un="clpp.npaw.YouboraPlugin",Vn="content.isLive",Wn=function(a){var b=youbora.Adapter.call(this,a)||this;b.a=a;b.c=new _.Xe;b.b=new _.E("clpp.npaw.YouboraAdapter");b.g=!1;b.f=!1;b.registerListeners();return b},Xn=function(a){a.plugin.isInitiated||(a.f=!1,a.fireInit())},Yn=function(a){var b=youbora.Adapter.call(this,a)||this;b.b=a;b.a=null;b.g=null;b.c=new _.Xe;b.f=new _.E("clpp.npaw.YouboraAdsAdapter");b.registerListeners();return b},Zn=function(){this.b=null;this.a=!1;this.c=new _.E(Un)},$n=
function(){};_.w(Wn,youbora.Adapter);_.r=Wn.prototype;_.r.getPlayhead=function(){return this.a.getPosition()};_.r.getDuration=function(){return this.a.getDuration()};_.r.getRendition=function(){var a=this.a.getTrackManager();if(a&&(a=a.V())){var b=a.width;var c=a.height;var d=a.bandwidth}b&&c&&d||(a=this.a.getStats()||_.ik(),b=b||a.width,c=c||a.height,d=d||a.streamBandwidth);return youbora.Util.buildRenditionString(b,c,d)};_.r.getIsLive=function(){return this.a.isLive()};
_.r.getResource=function(){var a=this.a.getLoadedSource();return a&&a.url};_.r.getBitrate=function(){return(this.a.getStats()||_.ik()).streamBandwidth};_.r.getThroughput=function(){return(this.a.getStats()||_.ik()).estimatedBandwidth};_.r.getPlayrate=function(){return this.a.getPlaybackRate()};_.r.getFramesPerSecond=function(){var a=this.a.getTrackManager();return a&&(a=a.ga())?a.frameRate:null};_.r.getPlayerName=function(){return _.la};_.r.getVersion=function(){return"6.0.4-castlabsadapter-js"};
_.r.getPlayerVersion=function(){return _.fa};_.r.registerListeners=function(){this.a&&this.c&&(this.b.debug("registering listeners"),this.monitorPlayhead(!0,!1),this.c.on(this.a,_.zd,this.Ri.bind(this)),this.c.on(this.a,_.zc,this.oh.bind(this)),this.c.on(this.a,_.Td,this.Rg.bind(this)),this.c.on(this.a,_.Sd,this.Qg.bind(this)),this.c.on(this.a,_.vb,this.Pf.bind(this)),this.c.on(this.a,_.Xb,this.Wf.bind(this)))};_.r.unregisterListeners=function(){this.b.debug("Unregistering listeners");_.$e(this.c)};
_.r.Ri=function(a){this.b.debug("State changed",a);if(a=a.detail)switch(a.currentState){case _.Mn:Xn(this);break;case _.el:Xn(this);this.fireStart();this.fireJoin();this.fireResume();this.fireBufferEnd();break;case _.Jm:Xn(this);this.fireBufferEnd();this.firePause();break;case _.ym:this.fireBufferEnd();this.fireStop();break;case _.Em:this.fireBufferEnd();this.g&&this.plugin.getAdsAdapter()||this.fireStop();break;case _.Cm:Xn(this);this.fireBufferBegin();break;default:this.b.debug("Unhandled state",
a)}};_.r.oh=function(a){this.b.debug("Fire error",a);!(a=a.detail)||this.f||10003===a.code&&this.plugin.getAdsAdapter()||(a.a===_.M?(this.f=!0,this.fireFatalError(""+a.code,a.message)):this.fireError(""+a.code,a.message))};_.r.Rg=function(a){this.b.debug("Seeking",a);Xn(this);this.fireSeekBegin()};_.r.Qg=function(a){this.b.debug("Seeked",a);this.fireSeekEnd()};_.r.Pf=function(a){this.b.debug("adsTimeline",a);a=a.adsTimeline;this.g=!!a&&a.tb()};_.r.Wf=function(a){this.b.debug("Casting",a);this.fireCasted()};_.w(Yn,youbora.Adapter);_.r=Yn.prototype;_.r.getDuration=function(){return this.a&&this.a.getDuration()};_.r.getRendition=function(){var a=null;this.a&&(a=youbora.Util.buildRenditionString(this.a.pb(),this.a.ob(),this.a.Ta()));return a};_.r.getBitrate=function(){return this.a&&this.a.Ta()};_.r.getPlayhead=function(){var a=this.b.getAdsManager();return a&&a.getPosition()};_.r.getResource=function(){return this.a&&this.a.getMediaUrl()};_.r.getTitle=function(){return this.a&&this.a.getTitle()};
_.r.getProvider=function(){return this.a&&this.a.getAdvertiserName()};_.r.getCreativeId=function(){return this.a&&this.a.getCreativeId()};_.r.getPosition=function(){var a=youbora.Constants.AdPosition,b=null;if(this.a)switch(this.a.qb()){case 0:b=a.Preroll;break;case 2:b=a.Postroll;break;case 1:b=a.Midroll}this.f.debug("Ad position",b);return b};_.r.getIsSkippable=function(){return this.a&&-1!==this.a.getSkipTimeOffset()};_.r.getAudioEnabled=function(){var a=this.b.getAdsManager();return a&&0<a.getVolume()};
_.r.getExpectedBreaks=function(){return this.g&&this.g.getCuePoints().length};_.r.getGivenBreaks=function(){return this.getExpectedBreaks()};_.r.getExpectedAds=function(){return this.a&&this.a.rb()};_.r.getGivenAds=function(){return this.getExpectedAds()};_.r.getBreaksTime=function(){var a=this;return this.g&&this.g.getCuePoints().map(function(b){return-1===b?a.b.getDuration():b})};_.r.getIsFullscreen=function(){this.b.getSurface();return!!document.fullscreenElement};_.r.getPlayerName=function(){return _.la};
_.r.getVersion=function(){return"6.0.4-castlabsadsadapter-js"};_.r.getPlayerVersion=function(){return _.fa};
_.r.registerListeners=function(){this.b&&this.c&&(this.c.on(this.b,_.vb,this.Of.bind(this)),this.c.on(this.b,_.qb,this.Mf.bind(this)),this.c.on(this.b,_.mb,this.Jf.bind(this)),this.c.on(this.b,_.ob,this.Kf.bind(this)),this.c.on(this.b,_.fb,this.Hf.bind(this)),this.c.on(this.b,_.gb,this.pd.bind(this,1)),this.c.on(this.b,_.jb,this.pd.bind(this,2)),this.c.on(this.b,_.sb,this.pd.bind(this,3)),this.c.on(this.b,_.eb,this.Gf.bind(this)),this.c.on(this.b,_.pb,this.Lf.bind(this)),this.c.on(this.b,_.zc,this.If.bind(this)),
this.c.on(this.b,_.bb,this.Uf.bind(this)),this.c.on(this.b,_.cb,this.Vf.bind(this)),this.c.on(this.b,_.db,this.gi.bind(this)),this.c.on(this.b,_.nb,this.Sg.bind(this)))};_.r.unregisterListeners=function(){_.$e(this.c)};_.r.Of=function(a){this.f.debug("ad timeline changed",a);this.g=a.adsTimeline};_.r.Mf=function(a){this.f.debug("ad start",a);this.a=a.ad;this.fireStart();this.fireJoin()};_.r.Hf=function(a){this.f.debug("ad end",a);this.fireStop()};_.r.Jf=function(a){this.f.debug("ad pause",a);this.firePause()};
_.r.Kf=function(a){this.f.debug("ad resume",a);this.fireResume()};_.r.gi=function(a){this.f.debug("on buffering",a);this.fireBufferBegin()};_.r.Sg=function(a){this.f.debug("on progress",a);this.fireBufferEnd()};_.r.pd=function(a,b){this.f.debug("ad quartile",a,b);this.fireQuartile(a)};_.r.Gf=function(a){this.f.debug("ad clicked",a);a=this.a&&this.a.Vb();this.f.debug("ad click through url: ",a);this.fireClick(a)};_.r.Lf=function(a){this.f.debug("ad skipped",a);this.fireSkip()};
_.r.Uf=function(a){this.f.debug("break start",a);this.a=a.ad;this.fireBreakStart()};_.r.Vf=function(a){this.f.debug("ad break stop",a);this.fireBreakStop();this.getPosition()===youbora.Constants.AdPosition.Postroll&&(a=this.plugin.getAdapter())&&a.fireStop()};_.r.If=function(a){this.f.warn("ad error",a);(a=a.detail)&&10003===a.code&&(a.a===_.M?this.fireFatalError(""+a.code,a.message):this.fireError(""+a.code,a.message))};_.w(Zn,_.tn);_.r=Zn.prototype;_.r.onPlayerCreated=function(){};
_.r.onContentWillLoad=function(a,b){var c=a.getConfiguration();(this.a=!_.J.H(c.youbora)&&typeof c.youbora===_.Xc)?window.youbora&&6<=+youbora.VERSION.split(".")[0]?a.namespace()===_.bc&&(this.a=!1,this.c.info("Youbora does not report when casting.")):(this.c.warn("No valid Youbora SDK available. Youbora SDK is supported","starting from version",6),this.a=!1,a.onError(new _.K(1,9,9100))):this.c.warn("Youbora plugin is loaded but not configured. Will do nothing.");if(this.a){var d=a.getConfiguration();
c=d.youbora;c.accountCode?(void 0===c[Vn]&&(c[Vn]=b.isLive),void 0===c["content.title"]&&(c["content.title"]=b.name),void 0===c.viewerId&&(c.viewerId=d.viewerId),d=new Wn(a),this.b=new youbora.Plugin(c,d),c=new Yn(a),this.b.setAdsAdapter(c)):(this.c.warn("accountCode key is missing"),a.onError(new _.K(1,9,9101)))}};_.r.onPlayerWillRelease=function(){this.a&&this.b&&(this.b.removeAdsAdapter(),this.b.removeAdapter(),this.b=null)};_.r.onPlayerWillDestroy=function(){};_.r.id=function(){return"youbora"};
_.B(Un,Zn);Zn.Id="youbora";$n.prototype.create=function(){return new Zn};_.hl(new $n);};f.call(g, window);