import {clpp} from "./cl.core.esm.js";let g={};var _ = clpp._;var f=function(window){var Ho="clpp.npaw.YouboraPlugin",Io="content.isLive",Jo=function(a){var b=youbora.Adapter.call(this,a)||this;b.a=a;b.c=new _.ii;b.b=new _.H("clpp.npaw.YouboraAdapter");b.g=!1;b.f=!1;b.registerListeners();return b},Ko=function(a){a.plugin.isInitiated||(a.f=!1,a.fireInit())},Lo=function(a){var b=youbora.Adapter.call(this,a)||this;b.b=a;b.a=null;b.g=null;b.c=new _.ii;b.f=new _.H("clpp.npaw.YouboraAdsAdapter");b.registerListeners();return b},Mo=function(){this.b=null;this.a=!1;this.c=new _.H(Ho)},No=
function(){};_.w(Jo,youbora.Adapter);_.r=Jo.prototype;_.r.getPlayhead=function(){return this.a.getPosition()};_.r.getDuration=function(){return this.a.getDuration()};_.r.getRendition=function(){var a=this.a.getTrackManager();if(a&&(a=a.Z())){var b=a.width;var c=a.height;var d=a.bandwidth}b&&c&&d||(a=this.a.getStats()||_.Vk(),b=b||a.width,c=c||a.height,d=d||a.streamBandwidth);return youbora.Util.buildRenditionString(b,c,d)};_.r.getIsLive=function(){return this.a.isLive()};
_.r.getResource=function(){var a=this.a.getLoadedSource();return a&&a.url};_.r.getBitrate=function(){return(this.a.getStats()||_.Vk()).streamBandwidth};_.r.getThroughput=function(){return(this.a.getStats()||_.Vk()).estimatedBandwidth};_.r.getPlayrate=function(){return this.a.getPlaybackRate()};_.r.getFramesPerSecond=function(){var a=this.a.getTrackManager();return a&&(a=a.ka())?a.frameRate:null};_.r.getPlayerName=function(){return _.ka};_.r.getVersion=function(){return"'6.1.2'-castlabsadapter-js"};
_.r.getPlayerVersion=function(){return _.da};_.r.registerListeners=function(){this.a&&this.c&&(this.b.debug("registering listeners"),this.monitorPlayhead(!0,!1),this.c.on(this.a,_.Dd,this.zj.bind(this)),this.c.on(this.a,_.Ac,this.Jh.bind(this)),this.c.on(this.a,_.Td,this.wj.bind(this)),this.c.on(this.a,_.Sd,this.vj.bind(this)),this.c.on(this.a,_.yb,this.hg.bind(this)),this.c.on(this.a,_.Zb,this.og.bind(this)))};_.r.unregisterListeners=function(){this.b.debug(_.Za);_.li(this.c)};
_.r.zj=function(a){this.b.debug("State changed",a);if(a=a.detail)switch(a.currentState){case _.Jn:Ko(this);break;case _.ln:Ko(this);this.fireStart();this.fireJoin();this.fireResume();this.fireBufferEnd();break;case _.Kn:Ko(this);this.fireBufferEnd();this.firePause();break;case _.yn:this.fireBufferEnd();this.fireStop();break;case _.En:this.fireBufferEnd();this.g&&this.plugin.getAdsAdapter()?this.firePause():this.fireStop();break;case _.Cn:Ko(this);this.fireBufferBegin();break;default:this.b.debug("Unhandled state",
a)}};_.r.Jh=function(a){this.b.debug("Fire error",a);!(a=a.detail)||this.f||10003===a.code&&this.plugin.getAdsAdapter()||(a.a===_.K?(this.f=!0,this.fireFatalError(""+a.code,a.message)):this.fireError(""+a.code,a.message))};_.r.wj=function(a){this.b.debug("Seeking",a);Ko(this);this.fireSeekBegin()};_.r.vj=function(a){this.b.debug("Seeked",a);this.fireSeekEnd()};_.r.hg=function(a){this.b.debug("adsTimeline",a);a=a.adsTimeline;this.g=!!a&&a.ab()};_.r.og=function(a){this.b.debug("Casting",a);this.fireCasted()};_.w(Lo,youbora.Adapter);_.r=Lo.prototype;_.r.getDuration=function(){return this.a&&this.a.getDuration()};_.r.getRendition=function(){var a=null;this.a&&(a=youbora.Util.buildRenditionString(this.a.Xa(),this.a.Wa(),this.a.Ja()));return a};_.r.getBitrate=function(){return this.a&&this.a.Ja()};_.r.getPlayhead=function(){var a=this.b.getAdsManager();return a&&a.getPosition()};_.r.getResource=function(){return this.a&&this.a.getMediaUrl()};_.r.getTitle=function(){return this.a&&this.a.getTitle()};
_.r.getProvider=function(){return this.a&&this.a.getAdvertiserName()};_.r.getCreativeId=function(){return this.a&&this.a.getCreativeId()};_.r.getPosition=function(){var a=youbora.Constants.AdPosition,b=null;if(this.a)switch(this.a.Aa()){case 0:b=a.Preroll;break;case 2:b=a.Postroll;break;case 1:b=a.Midroll}this.f.debug("Ad position",b);return b};_.r.getIsSkippable=function(){return this.a&&-1!==this.a.getSkipTimeOffset()};_.r.getAudioEnabled=function(){var a=this.b.getAdsManager();return a&&0<a.getVolume()};
_.r.getExpectedBreaks=function(){return this.g&&this.g.getCuePoints().length};_.r.getGivenBreaks=function(){return this.getExpectedBreaks()};_.r.getExpectedAds=function(){return this.a&&this.a.Za()};_.r.getGivenAds=function(){return this.getExpectedAds()};_.r.getBreaksTime=function(){var a=this;return this.g&&this.g.getCuePoints().map(function(b){return-1===b?a.b.getDuration():b})};_.r.getIsFullscreen=function(){this.b.getSurface();return!!document.fullscreenElement};_.r.getPlayerName=function(){return _.ka};
_.r.getVersion=function(){return"'6.1.2'-castlabsadsadapter-js"};_.r.getPlayerVersion=function(){return _.da};
_.r.registerListeners=function(){this.b&&this.c&&(this.c.on(this.b,_.yb,this.gg.bind(this)),this.c.on(this.b,_.tb,this.dg.bind(this)),this.c.on(this.b,_.ob,this.ag.bind(this)),this.c.on(this.b,_.qb,this.bg.bind(this)),this.c.on(this.b,_.ib,this.Zf.bind(this)),this.c.on(this.b,_.jb,this.yd.bind(this,1)),this.c.on(this.b,_.nb,this.yd.bind(this,2)),this.c.on(this.b,_.vb,this.yd.bind(this,3)),this.c.on(this.b,_.gb,this.Yf.bind(this)),this.c.on(this.b,_.sb,this.cg.bind(this)),this.c.on(this.b,_.Ac,this.$f.bind(this)),
this.c.on(this.b,_.db,this.mg.bind(this)),this.c.on(this.b,_.eb,this.ng.bind(this)),this.c.on(this.b,_.fb,this.Gi.bind(this)),this.c.on(this.b,_.pb,this.ih.bind(this)))};_.r.unregisterListeners=function(){_.li(this.c)};_.r.gg=function(a){this.f.debug("ad timeline changed",a);this.g=a.adsTimeline};_.r.dg=function(a){this.f.debug("ad start",a);this.a=a.ad;this.fireStart();this.fireJoin()};_.r.Zf=function(a){this.f.debug("ad end",a);this.fireStop()};_.r.ag=function(a){this.f.debug("ad pause",a);this.firePause()};
_.r.bg=function(a){this.f.debug("ad resume",a);this.fireResume()};_.r.Gi=function(a){this.f.debug("on buffering",a);this.fireBufferBegin()};_.r.ih=function(a){this.f.debug("on progress",a);this.fireBufferEnd()};_.r.yd=function(a,b){this.f.debug("ad quartile",a,b);this.fireQuartile(a)};_.r.Yf=function(a){this.f.debug("ad clicked",a);a=this.a&&this.a.nb();this.f.debug("ad click through url: ",a);this.fireClick(a)};_.r.cg=function(a){this.f.debug("ad skipped",a);this.fireSkip()};
_.r.mg=function(a){this.f.debug("break start",a);this.a=a.ad;this.fireBreakStart()};_.r.ng=function(a){this.f.debug("ad break stop",a);this.fireBreakStop();this.getPosition()===youbora.Constants.AdPosition.Postroll&&(a=this.plugin.getAdapter())&&a.fireStop()};_.r.$f=function(a){this.f.warn("ad error",a);(a=a.detail)&&10003===a.code&&(a.a===_.K?this.fireFatalError(""+a.code,a.message):this.fireError(""+a.code,a.message))};_.w(Mo,_.fo);_.r=Mo.prototype;_.r.onPlayerCreated=function(){};
_.r.onContentWillLoad=function(a,b){var c=a.getConfiguration();(this.a=!_.C.I(c.youbora)&&typeof c.youbora===_.$c)?window.youbora&&6<=+youbora.VERSION.split(".")[0]?a.namespace()===_.dc&&(this.a=!1,this.c.info("Youbora does not report when casting.")):(this.c.warn("No valid Youbora SDK available. Youbora SDK is supported","starting from version",6),this.a=!1,a.onError(new _.J(1,9,9100))):this.c.warn("Youbora plugin is loaded but not configured. Will do nothing.");if(this.a){var d=a.getConfiguration();
c=d.youbora;c.accountCode?(void 0===c[Io]&&(c[Io]=b.isLive),void 0===c["content.title"]&&(c["content.title"]=b.name),void 0===c.viewerId&&(c.viewerId=d.viewerId),d=new Jo(a),this.b=new youbora.Plugin(c,d),c=new Lo(a),this.b.setAdsAdapter(c)):(this.c.warn("accountCode key is missing"),a.onError(new _.J(1,9,9101)))}};_.r.onPlayerWillRelease=function(){this.a&&this.b&&(this.b.removeAdsAdapter(),this.b.removeAdapter(),this.b=null)};_.r.onPlayerWillDestroy=function(){};_.r.id=function(){return"youbora"};
_.B(Ho,Mo);Mo.Id="youbora";No.prototype.create=function(){return new Mo};_.xn(new No);};f.call(g, window);